<template>
  <div class="new-client">
    <v-overlay fixed :opacity="0.46" :value="showModal" :z-index="99" class="new-client__overlay">
      <v-card light class="new-client__container">
        <v-list-item class="pl-0 pr-0">
          <div class="v-btn v-cart-icon-wrapper">
            <v-icon medium left color="blue" class="ml-2">
              mdi-plus
            </v-icon>
          </div>
          <v-list-item-content class="pt-0 pb-0">
            <v-list-item-title class="v-card-headline">New Client</v-list-item-title>
          </v-list-item-content>
        </v-list-item>

        <v-list-item class="pl-0 pr-0">
          <v-list-item-content>
            <v-list-item-title class="new-client__title">
              Add New Integration Client
            </v-list-item-title>
            <v-list-item-subtitle class="new-client__subtitle">
              Add new client to provide integration service
            </v-list-item-subtitle>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0 mt-8">
          <v-list-item-content>
            <label class="new-client__label" for="client-name">Client Name</label>
            <v-list-item-subtitle class="new-client__api-key__subtitle">
              This name will respresent the client company
            </v-list-item-subtitle>
            <v-text-field
              placeholder="Enter Name"
              outlined
              class="new-client__textfield mt-2"
              v-model="formValues.clientName"
              required
              id="client-name"
              height="40"
            ></v-text-field>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content style="">
            <label class="new-client__label" for="generate-api-key"
              >Generate API Key for Keepnet Customer ID</label
            >
            <v-list-item-subtitle class="new-client__api-key__subtitle">
              Enter Keepnet Customer ID of the client to generate an API Key
            </v-list-item-subtitle>
            <v-text-field
              placeholder="Enter Customer ID  "
              outlined
              class="new-client__textfield mt-2"
              v-model="formValues.generateApiKey"
              required
              id="description"
              height="40"
            ></v-text-field>
            <v-btn class="generate-api" color="#2196f3" rounded @click="generateApiKey">
              GENERATE API KEY
            </v-btn>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-list-item-title class="new-client__label">
              API Key
            </v-list-item-title>
            <v-list-item-subtitle class="new-client__api-key__subtitle">
              Enter API Key generated by the provider
            </v-list-item-subtitle>
            <v-text-field
              placeholder="Generate API Key first"
              outlined
              class="new-client__textfield new-client__api-key__textfield mt-2"
              v-model="formValues.apiKey"
              required
              @input="handleApiKeyChange"
              height="40"
            />

            <v-btn class="copy-to-clipboard" color="#2196f3" rounded @click="generateApiKey">
              Copy to clipboard
            </v-btn>
          </v-list-item-content>
        </v-list-item>
      </v-card>
      <div class="new-client__footer">
        <v-btn class="new-client__footer-btn-cancel" rounded @click="closeOverlay">
          CANCEL
        </v-btn>
        <div class="new-client__footer__right-col">
          <v-btn class="new-client__footer-btn-save" color="#2196f3" rounded @click="submit">
            SAVE
          </v-btn>
        </div>
      </div>
    </v-overlay>
  </div>
</template>

<script>
import { COMMON_CONSTANTS } from '../../model/constants/commonConstants'
import { createClient, updateClient } from '../../api/clients'

export default {
  name: 'NewClients',
  props: {
    showModal: {
      type: Boolean,
      default: false
    },
    clientId: {
      type: String
    }
  },
  data() {
    return {
      formValues: {
        clientName: '',
        generateApiKey: '',
        apiKey: ''
      },
      isTestConnectionDisabled: true,
      apiKeys: ['']
    }
  },
  methods: {
    submit() {
      const data = this.formValues
      if (this.clientId) {
        updateClient(this.clientId, data)
          .then((response) => {
            this.closeOverlay()
            this.showConfirmModal = false
            this.$store.dispatch('common/createSnackBar', {
              errorState: false,
              color: COMMON_CONSTANTS.SUCCESSSNACKBARCOLOR,
              message: 'Integration updated successfuly!'
            })
          })
          .catch((error) => {
            this.$store.dispatch('common/createSnackBar', {
              errorState: true,
              color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
              message: 'Error when updating integration!'
            })
          })
      } else {
        createClient(data)
          .then((response) => {
            this.closeOverlay()
            this.showConfirmModal = false
            this.$store.dispatch('common/createSnackBar', {
              errorState: false,
              color: COMMON_CONSTANTS.SUCCESSSNACKBARCOLOR,
              message: 'Integration created successfuly!'
            })
          })
          .catch((error) => {
            this.$store.dispatch('common/createSnackBar', {
              errorState: true,
              color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
              message: 'Error when creating new integration!'
            })
          })
      }
    },
    closeOverlay() {
      this.$emit('closeOverlay', false)
    },
    addApiKey() {
      this.apiKeys.push('')
    },
    handleApiKeyChange() {
      this.isTestConnectionDisabled = true
      this.apiKeys.map((item) => {
        if (item.length > 0) {
          this.isTestConnectionDisabled = false
        }
      })
    },
    generateApiKey() {
      generateApiKey()
        .then((response) => {
          this.closeOverlay()
          this.showConfirmModal = false
          this.$store.dispatch('common/createSnackBar', {
            errorState: false,
            color: COMMON_CONSTANTS.SUCCESSSNACKBARCOLOR,
            message: 'Integration created successfuly!'
          })
        })
        .catch((error) => {
          this.$store.dispatch('common/createSnackBar', {
            errorState: true,
            color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
            message: 'Error when creating new integration!'
          })
        })
    }
  },
  destroyed() {
    this.clientId = null
    this.resetValues()
  }
}
</script>

<style lang="scss">
.new-client {
  .generate-api {
    border-radius: 18px;
    box-shadow: 0 2px 5px 0 rgba(100, 181, 246, 0.5);
    background-color: #2196f3;
    font-size: 14px;
    font-weight: 600;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.71;
    letter-spacing: normal;
    color: #ffffff;
    max-width: 160px;
    position: absolute;
    top: 54px;
    left: 570px;
  }
  .copy-to-clipboard {
    box-shadow: none !important;
    background-color: #fff !important;
    font-size: 14px;
    font-weight: 600;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.71;
    letter-spacing: normal;
    max-width: 160px;
    position: absolute;
    top: 54px;
    left: 570px;
    color: #2196f3 !important;
  }
  &__container {
    padding: 24px 0 0 96px !important;
    border-radius: 0 !important;
    box-shadow: none !important;

    &.v-card {
      padding: 24px 0 0 96px !important;
    }
  }

  &__overlay {
    .v-overlay__content {
      width: 100%;
      height: 100%;
      background-color: white;
      position: fixed;
      left: 0;
      top: 0;
      overflow-y: auto;
      padding-bottom: 68px !important;
    }
  }

  &__title {
    font-family: 'Open Sans', sans-serif !important;
    opacity: 0.9;
    font-size: 24px;
    line-height: 1.29;
    margin-top: 31px !important;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__subtitle {
    opacity: 0.9;
    font-family: 'Open Sans', sans-serif !important;
    font-size: 14px;
    font-weight: normal;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.5;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__label {
    font-family: 'Open Sans', sans-serif !important;
    font-size: 20px;
    font-weight: 600;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.2;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87);
  }

  &__select {
    max-width: 554px !important;
  }

  &__textfield {
    max-width: 554px !important;
  }

  &__footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    background-color: #f5f7fa;
    padding: 16px 96px !important;
    display: flex;
    justify-content: space-between;

    &-btn-cancel {
      color: #f56c6c !important;
      border: 1px solid #f56c6c !important;
      box-shadow: none !important;
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 86px;
      height: 36px !important;
    }

    &-btn-save {
      color: #ffffff;
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 72px;
      height: 36px !important;
      border-radius: 18px;
      box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.1), 0 2px 5px 0 rgba(33, 150, 243, 0.3);
      background-color: #2196f3;
    }
  }

  &__api-key {
    &__subtitle {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: normal;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.5;
      letter-spacing: normal;
      color: rgba(0, 0, 0, 0.87) !important;
    }

    &__textfield {
      ::v-deep .v-text-field__details {
        display: none !important;
      }
    }

    &__footer {
      display: flex;
      max-width: 554px !important;
      justify-content: space-between;
      align-items: center;

      &-left-side {
        display: flex;
        justify-content: center;
        align-items: center;
      }
    }

    &__text {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      color: #2196f3;
      cursor: pointer;
    }

    &__test-text {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      color: #757575 !important;
      opacity: 0.8;
    }
  }

  .v-list-item__content {
    padding: 0 !important;
  }
}

.theme--dark.v-btn:not(.v-btn--flat):not(.v-btn--text):not(.v-btn--outlined) {
  background-color: transparent;
}
</style>
