<template>
  <div class="new-integration">
    <v-overlay
      fixed
      :opacity="0.46"
      :value="showModal"
      :z-index="9999999"
      class="new-integration__overlay"
    >
      <v-card light class="new-integration__container">
        <v-list-item class="pl-0 pr-0">
          <div class="v-btn v-cart-icon-wrapper">
            <v-icon medium left color="blue" class="ml-2">
              mdi-plus
            </v-icon>
          </div>
          <v-list-item-content class="pt-0 pb-0">
            <v-list-item-title class="v-card-headline">New Client</v-list-item-title>
          </v-list-item-content>
        </v-list-item>

        <v-list-item class="pl-0 pr-0">
          <v-list-item-content>
            <v-list-item-title class="new-integration__title">
              Add New Integration Client
            </v-list-item-title>
            <v-list-item-subtitle class="new-integration__subtitle">
              Add new client to provide integration service
            </v-list-item-subtitle>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0 mt-8">
          <v-list-item-content>
            <label class="new-integration__label" for="client-name">Client Name</label>
            <v-text-field
              placeholder="Enter Name"
              outlined
              dense
              class="new-integration__textfield mt-2"
              v-model="formValues.integrationName"
              required
              id="client-name"
              height="40"
            ></v-text-field>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <label class="new-integration__label" for="generate-api-key"
              >Generate API Key for Keepnet Customer ID</label
            >
            <v-text-field
              placeholder="Enter Customer ID  "
              outlined
              dense
              class="new-integration__textfield mt-2"
              v-model="formValues.description"
              required
              id="description"
              height="40"
            ></v-text-field>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-list-item-title class="new-integration__label">
              API Key
            </v-list-item-title>
            <v-list-item-subtitle class="new-integration__api-key__subtitle">
              Enter API Key generated by the provider
            </v-list-item-subtitle>
            <div v-for="(item, index) in apiKeys.length" :key="index">
              <v-text-field
                placeholder="Enter API Key"
                outlined
                dense
                class="new-integration__textfield new-integration__api-key__textfield mt-2"
                v-model="apiKeys[index]"
                required
                @input="handleApiKeyChange"
                height="40"
              />
            </div>
          </v-list-item-content>
        </v-list-item>
      </v-card>
      <div class="new-integration__footer">
        <v-btn class="new-integration__footer-btn-cancel" rounded @click="closeOverlay">
          CANCEL
        </v-btn>
        <div class="new-integration__footer__right-col">
          <v-btn class="new-integration__footer-btn-save" color="#2196f3" rounded @click="submit">
            SAVE
          </v-btn>
        </div>
      </div>
    </v-overlay>
  </div>
</template>

<script>
export default {
  name: 'NewClients',
  props: {
    showModal: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      formValues: {
        integrationName: '',
        description: '',
        integrationType: '',
        tag: '',
        isActive: true,
        isSendUrl: false,
        isSendFileHash: true,
        isUploadExecutableFiles: true,
        isUploadOtherFiles: false
      },
      isTestConnectionDisabled: true,
      apiKeys: ['']
    }
  },
  methods: {
    submit() {},
    closeOverlay() {
      this.$emit('closeOverlay', false)
    },
    addApiKey() {
      this.apiKeys.push('')
    },
    handleApiKeyChange() {
      this.isTestConnectionDisabled = true
      this.apiKeys.map((item) => {
        if (item.length > 0) {
          this.isTestConnectionDisabled = false
        }
      })
    }
  }
}
</script>

<style lang="scss">
.new-integration {
  &__container {
    padding: 24px 0 0 96px !important;
    border-radius: 0 !important;
    box-shadow: none !important;

    &.v-card {
      padding: 24px 0 0 96px !important;
    }
  }

  &__overlay {
    .v-overlay__content {
      width: 100%;
      height: 100%;
      background-color: white;
      position: fixed;
      left: 0;
      top: 0;
      overflow-y: auto;
      padding-bottom: 68px !important;
    }
  }

  &__title {
    font-family: 'Open Sans', sans-serif !important;
    opacity: 0.9;
    font-size: 24px;
    line-height: 1.29;
    margin-top: 31px !important;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__subtitle {
    opacity: 0.9;
    font-family: 'Open Sans', sans-serif !important;
    font-size: 14px;
    font-weight: normal;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.5;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__label {
    font-family: 'Open Sans', sans-serif !important;
    font-size: 20px;
    font-weight: 600;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.2;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87);
  }

  &__select {
    max-width: 554px !important;
  }

  &__textfield {
    max-width: 554px !important;
  }

  &__footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    background-color: #f5f7fa;
    padding: 16px 96px !important;
    display: flex;
    justify-content: space-between;

    &-btn-cancel {
      color: #f56c6c !important;
      border: 1px solid #f56c6c !important;
      box-shadow: none !important;
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 86px;
      height: 36px !important;
    }

    &-btn-save {
      color: #ffffff;
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 72px;
      height: 36px !important;
      border-radius: 18px;
      box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.1), 0 2px 5px 0 rgba(33, 150, 243, 0.3);
      background-color: #2196f3;
    }
  }

  &__api-key {
    &__subtitle {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: normal;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.5;
      letter-spacing: normal;
      color: rgba(0, 0, 0, 0.87) !important;
    }

    &__textfield {
      ::v-deep .v-text-field__details {
        display: none !important;
      }
    }

    &__footer {
      display: flex;
      max-width: 554px !important;
      justify-content: space-between;
      align-items: center;

      &-left-side {
        display: flex;
        justify-content: center;
        align-items: center;
      }
    }

    &__text {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      color: #2196f3;
      cursor: pointer;
    }

    &__test-text {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      color: #757575 !important;
      opacity: 0.8;
    }
  }

  .v-list-item__content {
    padding: 0 !important;
  }
}

.theme--dark.v-btn:not(.v-btn--flat):not(.v-btn--text):not(.v-btn--outlined) {
  background-color: transparent;
}
</style>
