<template>
  <div class="new-integration">
    <v-overlay
      :style="showConfirmModal ? 'background-color:white' : ''"
      :value="showConfirmModal"
      :z-index="9999"
      class="new-integration__confirm-modal"
      fixed
    >
      <v-card class="new-integration__confirm-modal__container" light>
        <h2 class="new-integration__confirm-modal__header">
          Are you sure to upload files to this service?
        </h2>
        <p class="new-integration__confirm-modal__content">
          Files may carry sensitive information about your company
        </p>
        <div class="new-integration__confirm-modal__footer">
          <button
            class="new-integration__confirm-modal__btn-continue mr-3"
            @click="saveButtonClickOnConfirmModal"
          >
            YES, CONTINUE
          </button>
          <button
            class="new-integration__confirm-modal__btn-cancel"
            @click="cancelClickOnConfirmModal"
          >
            {{ labels.Cancel }}
          </button>
        </div>
      </v-card>
    </v-overlay>
    <app-modal
      v-if="showModal"
      :status="showModal"
      :title="integrationId ? 'Edit Integration' : 'New Integration'"
      icon-name="mdi-plus"
    >
      <template v-slot:overlay-body>
        <app-modal-body-header
          :title="integrationId ? 'Edit Integration' : 'Add New Integration'"
          sub-title="Add new integration to your Incident Responder"
        />
        <v-form ref="form" lazy-validation>
          <form-group title="Integration Name" has-hint>
            <v-text-field
              id="integration-name"
              v-model.trim="formValues.name"
              :rules="[nameValidation.required, nameValidation.empty, nameValidation.maxLength]"
              dense
              hint="*Required"
              persistent-hint
              outlined
              placeholder="Enter Name"
              required
            ></v-text-field>
          </form-group>
          <form-group title="Description">
            <v-text-field
              id="description"
              v-model.trim="formValues.description"
              :rules="[descriptionValidation.empty, descriptionValidation.maxLength]"
              dense
              outlined
              placeholder="Enter description"
            ></v-text-field>
          </form-group>
          <form-group title="Integration Type" has-hint>
            <k-select
              v-model.trim="formValues.analysisEngineTypeResourceId"
              :items="integrationTypes"
              :rules="[integrationTypeRules.required]"
              hint="*Required"
              persistent-hint
              dense
              item-text="name"
              item-value="resourceId"
              outlined
              placeholder="Select integration type"
              @input="handleIntegrationTypeChange"
            ></k-select>
          </form-group>
          <form-group title="API URL" has-hint>
            <v-text-field
              id="api-url"
              v-model.trim="formValues.apiUrl"
              :rules="[apiUrlRules.required, apiUrlRules.format, apiUrlRules.maxLength]"
              hint="*Required"
              persistent-hint
              dense
              height="40"
              outlined
              placeholder="Enter API URL"
              required
              @input="handleApiKeyChange"
            ></v-text-field>
          </form-group>
          <v-list-item class="px-0">
            <v-list-item-content>
              <v-list-item-title class="new-integration__label">
                API Key
              </v-list-item-title>
              <v-list-item-subtitle class="new-integration__api-key__subtitle">
                Enter API Key generated by the provider
              </v-list-item-subtitle>
              <div
                v-for="(item, index) in formValues.apiKeys"
                :key="item.status"
                class="position-relative new-integration__api-keys"
              >
                <div class="max-width__form">
                  <v-text-field
                    v-model.trim="item.value"
                    :class="item.status === 'failed' ? 'connection-error-state__border' : ''"
                    :rules="[apiKeyRules.required, apiKeyRules.format, apiKeyRules.maxLength]"
                    class="new-integration__textfield new-integration__api-key__textfield mt-2"
                    dense
                    height="40"
                    outlined
                    hint="*Required"
                    persistent-hint
                    placeholder="Enter API Key"
                    required
                    @input="handleApiKeyChange"
                  ></v-text-field>
                  <div
                    v-if="item.status === 'failed' && item.value.length > 0"
                    class="connection-error-state"
                  >
                    {{ item.errorMessage || 'Error' }}
                  </div>
                  <div v-if="!!item.status" class="new-integration__api-keys__connection-status">
                    <v-icon
                      v-if="item.status === 'loading'"
                      class="ml-1 loading-spin"
                      color="#00bcd4"
                      left
                      medium
                      >mdi-rotate-left
                    </v-icon>
                    <v-icon
                      v-if="item.status === 'success'"
                      class="ml-1"
                      color="#43a047"
                      left
                      medium
                      >mdi-check
                    </v-icon>
                    <v-icon
                      v-if="item.status === 'failed' && loadingState.length"
                      class="ml-1"
                      color="#f56c6c"
                      left
                      medium
                      >mdi-close
                    </v-icon>
                    <div v-if="item.status === 'failed' && !loadingState.length">
                      <button
                        :class="{
                          'new-integration__api-key__disabled-text': getTestConnectionDisableStatus()
                        }"
                        class="retry-button"
                        @click="retryTestConnection(item)"
                      >
                        RETRY
                      </button>
                    </div>
                  </div>
                  <div
                    :style="{ right: item.status ? '-100px' : '-40px' }"
                    class="new-integration__api-keys__delete"
                  >
                    <v-icon
                      v-if="formValues.apiKeys.length > 1"
                      class="ml-2"
                      left
                      medium
                      @click="formValues.apiKeys.splice(index, 1)"
                      >mdi-delete
                    </v-icon>
                  </div>
                </div>
              </div>
              <div></div>
              <div class="new-integration__api-key__footer">
                <div class="new-integration__api-key__footer-left-side" @click="addApiKey">
                  <v-icon color="#2196f3" style="cursor: pointer !important;">mdi-plus</v-icon>
                  <div class="ml-2 new-integration__api-key__text">ADD API KEY</div>
                </div>
                <div
                  :class="{
                    'new-integration__api-key__disabled-text': getTestConnectionDisableStatus()
                  }"
                  class="new-integration__api-key__text"
                  @click="testConnection(false)"
                >
                  <div v-if="loadingState.length" class="test-connection">
                    <v-icon class="ml-1 loading-spin" color="#00bcd4" left medium
                      >mdi-rotate-left
                    </v-icon>
                    TESTING CONNECTION
                  </div>
                  <div
                    v-else
                    :class="{
                      'new-integration__api-key__disabled-text': getTestConnectionDisableStatus()
                    }"
                    class="test-connection"
                  >
                    TEST CONNECTION
                  </div>
                </div>
              </div>
            </v-list-item-content>
          </v-list-item>
          <v-list-item class="px-0 mt-3">
            <v-list-item-content>
              <v-list-item-title class="new-integration__label">
                Tags
              </v-list-item-title>
              <v-list-item-subtitle class="new-integration__api-key__subtitle">
                Use enter key to use tags
              </v-list-item-subtitle>
              <div class="max-width__form new-integration__api-key__combobox">
                <k-select
                  type="combobox"
                  v-model.trim="formValues.tags"
                  :items="[]"
                  :return-object="false"
                  class="edit-select standard-height mt-2"
                  deletable-chips
                  dense
                  item-text="name"
                  multiple
                  outlined
                  persistent-hint
                  placeholder="Enter Tag"
                  small-chips
                  @input="handleTagItemChange"
                />
              </div>
            </v-list-item-content>
          </v-list-item>

          <v-list-item class="px-0" v-if="selectedIntegrationType.isSendUrl">
            <v-list-item-content>
              <label class="new-integration__label">URLs</label>
              <div class="mt-1">
                <v-checkbox
                  v-model="formValues.isSendUrl"
                  :label="`Share URLs in emails with integrated service`"
                  color="#2196f3"
                />
              </div>
              <div
                v-if="formValues.isSendUrl && selectedIntegrationType.isSendUrl"
                class="new-integration__api-key__subtitle__upload-subtitle position-relative checkbox-tooltip"
              >
                <v-checkbox
                  v-model="formValues.isHideUrlParameter"
                  :label="`Hide URL Parameters`"
                  class="black--text"
                  color="#2196f3"
                ></v-checkbox>
                <v-tooltip bottom opacity="1">
                  <template v-slot:activator="{ on: tooltip }">
                    <v-icon v-on="{ ...tooltip }">mdi-help-circle</v-icon>
                  </template>
                  <span class="tooltip-span" style="max-width: 50px;">{{
                    'Send URLs without query string parameters'
                  }}</span>
                </v-tooltip>
              </div>
            </v-list-item-content>
          </v-list-item>
          <v-list-item
            class="px-0 mt-6 mb-6"
            v-if="
              selectedIntegrationType.isSendUrl ||
              selectedIntegrationType.isSendFileHash ||
              selectedIntegrationType.isSendUrl
            "
          >
            <v-list-item-content>
              <v-list-item-title class="new-integration__label">
                Attachments
              </v-list-item-title>
              <v-list-item-subtitle class="new-integration__api-key__subtitle">
                Uploading originally attached files to integrated services may lead sensitive
                information to be compromised
              </v-list-item-subtitle>
              <v-checkbox
                v-model="formValues.isSendFileHash"
                :label="`Share file hashes (MD5, SHA256 and SHA512)`"
                style="margin-top: 10px;"
                color="#2196f3"
                v-if="selectedIntegrationType.isSendFileHash"
              ></v-checkbox>
              <div v-if="selectedIntegrationType.isSendFile">
                <v-checkbox
                  v-model="formValues.isSendFile"
                  :label="`Upload PE files`"
                  color="#2196f3"
                ></v-checkbox>
                <div
                  class="new-integration__api-key__subtitle__upload-subtitle position-relative ml-8"
                  style="font-size: 14px; line-height: 1.5;"
                >
                  Portable executable files (exe, .dll, .sys, etc.)
                </div>
                <div>
                  <v-checkbox
                    v-model="formValues.isUploadOtherFileType"
                    :label="`Upload other file types`"
                    color="#2196f3"
                  />
                </div>
                <div
                  v-if="formValues.isUploadOtherFileType"
                  class="new-integration__api-key__subtitle__upload-subtitle position-relative checkbox-tooltip"
                >
                  <div v-if="formValues.isUploadOtherFileType" class="ml-8 mt-1">
                    <div class="d-flex align-center">
                      <span class="mr-4 type-text">File Types</span>
                      <k-select
                        v-model.trim="formValues.uploadFileTypes"
                        :items="uploadFileTypes"
                        class="new-integration__select"
                        dense
                        multiple
                        outlined
                        hide-details
                        placeholder="Select integration type"
                        required
                      ></k-select>
                    </div>
                  </div>
                </div>
              </div>
            </v-list-item-content>
          </v-list-item>

          <v-list-item class="px-0">
            <v-list-item-content class="pl-3">
              <v-list-item-title class="new-integration__label">
                Status
              </v-list-item-title>
              <v-list-item-subtitle class="new-integration__api-key__subtitle">
                Activate and deactivate integration
              </v-list-item-subtitle>
              <v-switch
                class="playbook-rule-form__switch mt-4"
                v-model="formValues.isActive"
                :label="formValues.isActive ? 'Active' : 'Inactive'"
                color="#2196f3"
              />
            </v-list-item-content>
          </v-list-item>
        </v-form>
      </template>
      <template v-slot:overlay-footer>
        <v-btn
          class="new-integration__footer-btn-cancel"
          rounded
          @click="$emit('closeOverlay', false, false)"
        >
          {{ labels.Cancel }}
        </v-btn>
        <div class="new-integration__footer__right-col">
          <v-btn
            class="new-integration__footer-btn-save white--text"
            color="#2196f3"
            rounded
            @click="submit"
            :disabled="saveDisable"
          >
            {{ labels.Save }}
          </v-btn>
        </div>
      </template>
    </app-modal>
  </div>
</template>

<script>
import {
  createIntegration,
  getFileTypes,
  getIntegrationDetails,
  getIntegrationTypes,
  testAnalysis,
  updateIntegration
} from '@/api/integrations'
import { COMMON_CONSTANTS } from '@/model/constants/commonConstants'
import AppModal from '../AppModal'
import { scrollToComponent } from '@/utils/functions'
import AppModalBodyHeader from '@/components/SmallComponents/AppModalBodyHeader'
import FormGroup from '@/components/SmallComponents/FormGroup'
import KSelect from '@/components/Common/Inputs/KSelect'
import labels from '@/model/constants/labels'
import * as Validations from '@/utils/validations'
export default {
  name: 'NewIntegration',
  components: {
    KSelect,
    FormGroup,
    AppModal,
    AppModalBodyHeader
  },
  props: {
    showModal: {
      type: Boolean,
      default: false
    },
    integrationId: {
      type: String
    }
  },
  data() {
    return {
      saveDisable: false,
      labels,
      loadingState: [],
      formValues: {
        description: null,
        analysisEngineTypeResourceId: null,
        tags: [],
        isActive: true,
        isSendUrl: false,
        isSendFileHash: false,
        isUploadExecutableFile: false,
        isUploadOtherFileType: false,
        apiKeys: [{ value: '', status: null }],
        isHideUrlParameter: false,
        uploadFileTypes: [],
        name: null,
        apiUrl: null
      },
      selectedIntegrationType: {
        isSendUrl: false,
        isSendFileHash: false,
        isSendFile: false
      },
      integrationTypes: [],
      uploadFileTypes: [],
      isTestConnectionDisabled: true,
      showConfirmModal: false,
      nameValidation: {
        required: (v) => Validations.required(v),
        maxLength: (v) =>
          Validations.maxLength(v, 64, labels.getMaxLengthMessage('Integration name')),
        empty: (v) => Validations.startsWithSpace(v)
      },
      descriptionValidation: {
        maxLength: (v) =>
          Validations.maxLength(v, 300, labels.getMaxLengthMessage('Description', 300)),
        empty: (v) => Validations.startsWithSpace(v)
      },
      integrationTypeRules: {
        required: (v) => Validations.required(v),
        format: (v) => Validations.startsWithSpace(v)
      },
      apiUrlRules: {
        required: (v) => Validations.required(v),
        format: (v) => Validations.url(v),
        maxLength: (v) => Validations.maxLength(v, 1000, labels.getMaxLengthMessage('URL', 1000))
      },
      apiKeyRules: {
        required: (v) => Validations.required(v),
        format: (v) => Validations.startsWithSpace(v),
        maxLength: (v) => Validations.maxLength(v, 256, labels.getMaxLengthMessage('Api key', 256))
      }
    }
  },
  created() {
    if (this.integrationId) this.updateVModel(this.integrationId)
    getIntegrationTypes()
      .then((response) => {
        const {
          data: { data }
        } = response

        this.integrationTypes = data
        this.selectedIntegrationType =
          this.integrationTypes.find(
            (item) => item.resourceId === this.formValues.analysisEngineTypeResourceId
          ) || {}
      })
      .catch(() => {
        this.$store.dispatch('common/createSnackBar', {
          color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
          message: 'Error when getting integrations type'
        })
      })
    this.getFileTypes()
  },
  methods: {
    saveIntegration() {
      const data = { ...this.formValues }
      data.apiKeys = data.apiKeys.map((i) => i.value)
      if (this.integrationId) {
        updateIntegration(this.integrationId, data)
          .then(() => {
            this.saveDisable = false
            this.closeOverlay()
            this.showConfirmModal = false
          })
          .catch(() => {
            this.$store.dispatch('common/createSnackBar', {
              errorState: true,
              color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
              message: 'Integration can not be updated'
            })
            this.saveDisable = false
          })
      } else {
        createIntegration(data)
          .then(() => {
            this.closeOverlay()
            this.showConfirmModal = false
          })
          .finally(() => {
            this.saveDisable = false
          })
      }
    },
    handleTagItemChange(value) {
      value[value.length - 1] = value[value.length - 1].substring(0, 20)
    },
    submit() {
      const refForm = this.$refs.form
      const isValidForm = refForm.validate()
      if (isValidForm) {
        this.saveDisable = true
        this.testConnection(true)
      } else {
        return this.$nextTick(() => {
          const el = refForm.$el.querySelector('.error--text')
          scrollToComponent(el)
        })
      }
    },
    closeOverlay() {
      this.$emit('closeOverlay', false, true)
    },
    getTestConnectionDisableStatus() {
      if (
        this.formValues.apiUrl &&
        this.formValues.apiKeys[0].value.length > 0 &&
        typeof this.apiUrlRules.format(this.formValues.apiUrl) !== 'string'
      ) {
        return false
      } else {
        return true
      }
    },
    saveButtonClickOnConfirmModal() {
      if (!this.uploadFileTypes.length) this.getFileTypes()
      this.showConfirmModal = false
    },
    getFileTypes() {
      getFileTypes()
        .then((response) => {
          const {
            data: { data, status }
          } = response
          this.uploadFileTypes = data.map((item) => {
            switch (item.name) {
              case 'Archive':
                return { text: 'Archive files (.zip, .rar)', value: item.name }
              case 'Image':
                return { text: 'Image files (.jpg, .png, .gif, .bmp)', value: item.name }
              case 'Microsoft Office':
                return {
                  text: 'Microsoft Office files (.doc, .docx, .xls, .xlsx, .ppt, .pptx, etc.)',
                  value: item.name
                }
              case 'Other':
                return { text: 'Other', value: item.name }
              default:
                return { text: item.name, value: item.name }
            }
          })
        })
        .catch((error) => {
          this.$store.dispatch('common/createSnackBar', {
            color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
            message: 'Error when getting file types! '
          })
        })
    },
    addApiKey() {
      this.isTestConnectionDisabled = true
      this.formValues.apiKeys.push({ value: '', status: null })
    },
    handleApiKeyChange() {
      if (!this.formValues.apiUrl) return true
      this.formValues.apiKeys.map((item) => {
        this.isTestConnectionDisabled = false
        if (!item.value.length) {
          this.isTestConnectionDisabled = true
          return true
        }
      })
    },
    cancelClickOnConfirmModal() {
      this.formValues.uploadFileTypes = []
      this.formValues.isUploadOtherFileType = false
      this.showConfirmModal = false
    },
    updateIntegration() {
      updateIntegration()
        .then((response) => {})
        .catch((error) => {
          this.$store.dispatch('common/createSnackBar', {
            color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
            message: 'Error when updating the integration!'
          })
        })
    },
    updateVModel(id) {
      getIntegrationDetails(id)
        .then((response) => {
          response['data'].data.apiKeys = response['data'].data.apiKeys.map((item) => {
            return { value: item, status: null }
          })
          const integrationData = response['data'].data
          this.formValues = integrationData
        })
        .catch((error) => {
          this.$store.dispatch('common/createSnackBar', {
            color: COMMON_CONSTANTS.ERRORSNACKBARCOLOR,
            message: 'Error when getting integration details!'
          })
        })
    },
    resetValues() {
      this.formValues = {
        description: null,
        analysisEngineTypeResourceId: null,
        tags: null,
        isActive: true,
        isSendUrl: false,
        isSendFileHash: true,
        isUploadExecutableFile: true,
        isUploadOtherFileType: false,
        apiKeys: [{ value: '', status: null }],
        isHideUrlParameter: false,
        uploadFileTypes: [],
        name: null,
        apiUrl: null
      }
    },
    retryTestConnection(item) {
      item.status = 'loading'
      this.loadingState.push('loading')
      testAnalysis(this.formValues.analysisEngineTypeResourceId, item.value)
        .then((response) => {
          if (response.data.status === 'FAILED') {
            item.status = 'failed'
            this.formValues.apiKeys[i].errorMessage = response.data.message
          } else {
            item.status = 'success'
          }
          item.status = 'success'
        })
        .catch((error) => {
          item.status = 'failed'
          if (error.response.data.Message === 'Internal server error') {
            item.errorMessage = 'Error when testing connections!'
          } else {
            item.errorMessage = error.response.data.message || error.response.data.Message
          }
        })
        .finally(() => this.loadingState.shift('loading'))
    },
    testConnection(isSave) {
      for (let i = 0; i < this.formValues.apiKeys.length; i++) {
        const item = this.formValues.apiKeys[i]
        this.formValues.apiKeys[i].status = 'loading'
        this.loadingState.push('loading')
        testAnalysis(this.formValues.analysisEngineTypeResourceId, item.value)
          .then((response) => {
            if (response.data.status === 'FAILED') {
              this.formValues.apiKeys[i].status = 'failed'
              this.formValues.apiKeys[i].errorMessage = response.data.message
            } else {
              this.formValues.apiKeys[i].status = 'success'
            }
            this.saveDisable = false
          })
          .catch((error) => {
            this.saveDisable = false
            this.formValues.apiKeys[i].status = 'failed'
            if (error.response.data.Message === 'Internal server error') {
              this.formValues.apiKeys[i].errorMessage = 'Error when testing connections!'
            } else {
              this.formValues.apiKeys[i].errorMessage =
                error.response.data.message || error.response.data.Message
            }
          })
          .finally(() => {
            this.loadingState.shift('loading')
            if (
              isSave &&
              !this.loadingState.length &&
              !this.formValues.apiKeys.find((item) => item.status === 'failed')
            )
              this.saveIntegration()
          })
      }
    },
    handleIntegrationTypeChange(val) {
      this.selectedIntegrationType = this.integrationTypes.find((item) => item.resourceId === val)
      if (this.selectedIntegrationType.name === 'VirusTotal') {
        this.formValues.isSendUrl = true
        this.formValues.isSendFileHash = true
        this.formValues.apiUrl = 'https://www.virustotal.com/vtapi/v2'
      }
    }
  },
  destroyed() {},
  watch: {
    formValues(val) {
      this.selectedIntegrationType =
        this.integrationTypes.find(
          (item) => item.resourceId === val.analysisEngineTypeResourceId
        ) || {}
    }
  }
}
</script>

<style lang="scss">
.loading-spin {
  animation-name: spin;
  animation-duration: 1000ms;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
}

@keyframes spin {
  from {
    transform: rotate(360deg);
  }
  to {
    transform: rotate(0deg);
  }
}

.position-relative {
  position: relative;
}

.max-width__form {
  position: relative;
  max-width: 554px !important;
}

.new-integration {
  .edit-select {
    .v-input__append-inner {
      display: none;
    }
  }

  .v-list-item {
    //margin-bottom: 1px;
  }

  .v-list-item__content > *:not(:last-child) {
    margin-bottom: 0;
  }

  .new-integration__api-key__textfield {
    .v-text-field__details {
      margin-bottom: 0;
    }
  }

  .connection-error-state {
    font-size: 9px;
    font-weight: normal;
    font-stretch: normal;
    font-style: normal;
    line-height: normal;
    letter-spacing: normal;
    background: white;
    color: #ff5252 !important;

    position: absolute;
    top: 42px;
    left: 13px;

    &__border {
      fieldset {
        border-color: #d0021b;
      }
    }
  }

  .test-connection {
    font-size: 14px;
    font-weight: 600;
    line-height: 1.71;
    letter-spacing: normal;
    text-align: center;
    color: #00bcd4;
  }

  .retry-button {
    color: #f56c6c;
    font-size: 14px;
    font-weight: 600;
    line-height: 1.71;
    letter-spacing: normal;
  }

  &__container {
    padding: 24px 0 0 96px !important;
    border-radius: 0 !important;
    box-shadow: none !important;
  }

  &__api-keys {
    &:hover {
      .new-integration__api-keys__delete {
        display: flex;
      }
    }

    &__connection-status {
      width: 44px;
      height: 40px;
      color: #757575;
      position: absolute;
      right: -50px;
      top: 6px;
      justify-content: center;
    }

    &__delete {
      width: 44px;
      height: 40px;
      color: #757575;
      position: absolute;
      right: -40px;
      top: -2px;
      justify-content: center;
      display: none;
    }
  }

  &__overlay {
    .v-overlay__content {
      width: 100%;
      height: 100%;
      background-color: white;
      position: fixed;
      left: 0;
      top: 0;
      overflow-y: auto;
      padding-bottom: 68px !important;
    }
  }

  &__title {
    font-family: 'Open Sans', sans-serif !important;
    opacity: 0.9;
    font-size: 24px;
    font-weight: normal;
    line-height: 1.29 !important;
    margin-top: 31px !important;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__subtitle {
    opacity: 0.9;
    font-family: 'Open Sans', sans-serif !important;
    font-size: 14px;
    font-weight: normal;
    line-height: 1.5 !important;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__label {
    font-size: 20px;
    font-weight: 600;
    line-height: 1.2;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87);
  }

  &__select {
    max-width: 554px !important;
  }

  &__textfield {
    max-width: 554px !important;
  }

  &__footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    background-color: #f5f7fa;
    padding: 16px 96px !important;
    display: flex;
    justify-content: space-between;

    &-btn-cancel {
      color: #f56c6c !important;
      border: 1px solid #f56c6c !important;
      box-shadow: none !important;
      font-size: 14px;
      font-weight: 600;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 86px;
      height: 36px !important;
    }

    &-btn-save {
      color: #ffffff;
      font-size: 14px;
      font-weight: 600;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 72px;
      height: 36px !important;
      border-radius: 18px;
      box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.1), 0 2px 5px 0 rgba(33, 150, 243, 0.3);
      background-color: #2196f3;
    }
  }

  &__api-key {
    &__subtitle {
      font-size: 14px;
      font-weight: normal;
      line-height: 1.5 !important;
      letter-spacing: normal;
      color: rgba(0, 0, 0, 0.87) !important;

      &__upload-subtitle {
        margin-left: 30px;
      }
    }

    &__combobox {
      .v-chip {
        margin: 4px !important;
      }
    }

    &__textfield {
      ::v-deep .v-text-field__details {
        display: none !important;
      }
    }

    &__footer {
      display: flex;
      max-width: 554px !important;
      justify-content: space-between;
      align-items: center;
      margin-top: 6px;
      margin-bottom: 12px;

      &-left-side {
        display: flex;
        justify-content: center;
        align-items: center;
      }
    }

    &__text {
      font-size: 14px;
      font-weight: 600;
      line-height: 1.71;
      letter-spacing: normal;
      color: #2196f3;
      cursor: pointer;
    }

    &__test-text {
      font-size: 14px;
      font-weight: 600;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      color: #757575 !important;
      opacity: 0.8;
    }

    &__disabled-text {
      font-size: 14px;
      font-weight: 600;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      color: #757575 !important;
      opacity: 0.8;
      pointer-events: none !important;
    }
  }

  &.v-card {
    padding: 24px 0 0 96px !important;
  }

  .v-input--switch {
    .v-label {
      font-size: 20px;
      font-weight: 600;
      line-height: 1.2;
      letter-spacing: normal;
      color: rgba(0, 0, 0, 0.87);
    }
  }

  .type-text {
    font-size: 14px;
    font-weight: 600;
    line-height: 1.5;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  .v-list-item__content {
    padding: 0 !important;
  }

  .v-input--checkbox {
    .v-messages {
      display: none;
    }
  }

  .checkbox-tooltip {
    .mdi-help-circle {
      position: absolute;
      top: 3px;
      left: 180px;
    }
  }
}

.new-integration__confirm-modal {
  .v-overlay__scrim {
    opacity: 0 !important;
    background-color: white !important;
  }

  &__header {
    padding: 32px 24px;
    font-size: 20px;
    font-weight: 600;

    line-height: 1.15;
    letter-spacing: normal;
    color: #2196f3;
  }

  &__content {
    font-size: 13px;
    font-weight: 600;
    line-height: normal;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.54);
    padding: 8px 24px;
  }

  &__footer {
    padding: 16px 24px;
    text-align: right;
  }

  &__btn-continue {
    font-size: 14px;
    font-weight: 600;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.71;
    letter-spacing: normal;
    color: #2196f3;
  }

  &__btn-cancel {
    font-size: 14px;
    font-weight: 600;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.71;
    letter-spacing: normal;
    text-align: center;
    color: #f56c6c;
  }
}
</style>
