<template>
  <div class="new-integration">
    <v-overlay fixed :opacity="0.46" :value="showModal" :z-index="9999999">
      <v-card light class="new-integration__container">
        <v-list-item class="pl-0 pr-0">
          <div class="v-btn v-cart-icon-wrapper">
            <v-icon medium left color="blue" class="ml-2">
              mdi-plus
            </v-icon>
          </div>
          <v-list-item-content class="pt-0 pb-0">
            <v-list-item-title class="v-card-headline">New Integration</v-list-item-title>
          </v-list-item-content>
        </v-list-item>

        <v-list-item class="pl-0 pr-0">
          <v-list-item-content>
            <v-list-item-title class="new-integration__title">
              Add New Integration
            </v-list-item-title>
            <v-list-item-subtitle class="new-integration__subtitle">
              Add new integration to your Incident Responder
            </v-list-item-subtitle>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0 mt-8">
          <v-list-item-content>
            <label class="new-integration__label" for="integration-name">Integration Name</label>
            <v-text-field
              placeholder="Enter Name"
              outlined
              dense
              class="new-integration__textfield mt-2"
              v-model="formValues.integrationName"
              required
              id="integration-name"
              height="40"
            ></v-text-field>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <label class="new-integration__label" for="description">Description</label>
            <v-text-field
              placeholder="Enter description"
              outlined
              dense
              class="new-integration__textfield mt-2"
              v-model="formValues.description"
              required
              id="description"
              height="40"
            ></v-text-field>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <label class="new-integration__label" for="integration-type">Integration Type</label>
            <v-select
              :items="[]"
              v-model="formValues.integrationType"
              outlined
              class="new-integration__select"
              required
              dense
              placeholder="Select integration type"
              height="40"
            ></v-select>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <label class="new-integration__label" for="api-url">API URL</label>
            <v-text-field
              placeholder="Enter API URL"
              outlined
              dense
              class="new-integration__textfield mt-2"
              v-model="formValues.integrationType"
              required
              id="api-url"
              height="40"
            ></v-text-field>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-list-item-title class="new-integration__label">
              API Key
            </v-list-item-title>
            <v-list-item-subtitle class="new-integration__api-key__subtitle">
              Enter API Key generated by the provider
            </v-list-item-subtitle>
            <div v-for="(item, index) in apiKeys.length" :key="index">
              <v-text-field
                placeholder="Enter API Key"
                outlined
                dense
                class="new-integration__textfield new-integration__api-key__textfield mt-2"
                v-model="apiKeys[index]"
                required
                @input="handleApiKeyChange"
                height="40"
              ></v-text-field>
            </div>
            <div></div>
            <div class="new-integration__api-key__footer">
              <div class="new-integration__api-key__footer-left-side" @click="addApiKey">
                <v-icon color="#2196f3" style="cursor: pointer !important;">mdi-plus</v-icon>
                <div class="ml-2 new-integration__api-key__text">ADD API KEY</div>
              </div>
              <div
                class="new-integration__api-key__text"
                :disabled="isTestConnectionDisabled"
                :class="{ 'new-integration__api-key__test-text': isTestConnectionDisabled }"
              >
                TEST CONNECTION
              </div>
            </div>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0 mt-3">
          <v-list-item-content>
            <v-list-item-title class="new-integration__label">
              Tags
            </v-list-item-title>
            <v-list-item-subtitle class="new-integration__api-key__subtitle">
              Use enter key to use tags
            </v-list-item-subtitle>
            <v-text-field
              placeholder="Enter tag"
              outlined
              dense
              class="new-integration__textfield mt-2"
              v-model="formValues.tag"
              required
              height="40"
            ></v-text-field>
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-switch v-model="formValues.isActive" color="#2196f3" label="Active" />
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-switch v-model="formValues.isSendUrl" label="Send URL" />
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-switch v-model="formValues.isSendFileHash" label="Send file hash" />
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-switch
              v-model="formValues.isUploadExecutableFiles"
              label="Upload executables files"
            />
          </v-list-item-content>
        </v-list-item>
        <v-list-item class="px-0">
          <v-list-item-content>
            <v-switch v-model="formValues.isUploadOtherFiles" label="Upload other files" />
          </v-list-item-content>
        </v-list-item>
        <div style="max-width: 554px;" class="mb-8 mt-n4 new-integration__api-key__subtitle">
          Uploading the originally attached files to integrated services may lead sensitive
          information to be compromised
        </div>
      </v-card>
      <div class="new-integration__footer">
        <v-btn class="new-integration__footer-btn-cancel" rounded @click="closeOverlay">
          CANCEL
        </v-btn>
        <div class="new-integration__footer__right-col">
          <v-btn class="new-integration__footer-btn-save" color="#2196f3" rounded @click="submit">
            SAVE
          </v-btn>
        </div>
      </div>
    </v-overlay>
  </div>
</template>

<script>
export default {
  name: 'NewIntegration',
  props: {
    showModal: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      formValues: {
        integrationName: '',
        description: '',
        integrationType: '',
        tag: '',
        isActive: true,
        isSendUrl: false,
        isSendFileHash: true,
        isUploadExecutableFiles: true,
        isUploadOtherFiles: false
      },
      isTestConnectionDisabled: true,
      apiKeys: ['']
    }
  },
  methods: {
    submit() {},
    closeOverlay() {
      this.$emit('closeOverlay', false)
    },
    addApiKey() {
      this.apiKeys.push('')
    },
    handleApiKeyChange() {
      this.isTestConnectionDisabled = true
      this.apiKeys.map((item) => {
        if (item.length > 0) {
          this.isTestConnectionDisabled = false
        }
      })
    }
  }
}
</script>

<style scoped lang="scss">
.v-cart-icon-wrapper {
  width: 48px;
  height: 48px;
  border-radius: 10px;
  margin-right: 24px;
  box-shadow: 0 2px 20px 0 rgba(100, 181, 246, 0.5);
  border: solid 1px rgba(100, 181, 246, 0.5);
  background-color: #e3f2fd;
}

.v-card-headline {
  font-family: 'Open Sans', sans-serif !important;
  font-size: 20px;
  font-weight: 600;
  font-stretch: normal;
  font-style: normal;
  line-height: 1.4;
  letter-spacing: normal;
  color: #000;
}

::v-deep .v-overlay__content {
  width: 100%;
  height: 100%;
  background-color: white;
  position: fixed;
  left: 0;
  top: 0;
  overflow-y: auto;
  padding-bottom: 68px !important;
}

.new-integration {
  &__container {
    padding: 24px 0 0 96px !important;
    border-radius: 0 !important;
  }

  &__title {
    font-family: 'Open Sans', sans-serif !important;
    opacity: 0.9;
    font-size: 24px;
    font-weight: normal;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.29;
    margin-top: 31px !important;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__subtitle {
    opacity: 0.9;
    font-family: 'Open Sans', sans-serif !important;
    font-size: 14px;
    font-weight: normal;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.5;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87) !important;
  }

  &__label {
    font-family: 'Open Sans', sans-serif !important;
    font-size: 20px;
    font-weight: 600;
    font-stretch: normal;
    font-style: normal;
    line-height: 1.2;
    letter-spacing: normal;
    color: rgba(0, 0, 0, 0.87);
  }

  &__select {
    max-width: 554px !important;
  }

  &__textfield {
    max-width: 554px !important;
  }

  &__footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    background-color: #f5f7fa;
    padding: 16px 96px !important;
    display: flex;
    justify-content: space-between;

    &-btn-cancel {
      color: #f56c6c !important;
      border: 1px solid #f56c6c !important;
      box-shadow: none !important;
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 86px;
      height: 36px !important;
    }

    &-btn-save {
      color: #ffffff;
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      width: 72px;
      height: 36px !important;
      border-radius: 18px;
      box-shadow: 0 0 3px 0 rgba(0, 0, 0, 0.1), 0 2px 5px 0 rgba(33, 150, 243, 0.3);
      background-color: #2196f3;
    }
  }

  &__api-key {
    &__subtitle {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: normal;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.5;
      letter-spacing: normal;
      color: rgba(0, 0, 0, 0.87) !important;
    }

    &__textfield {
      ::v-deep .v-text-field__details {
        display: none !important;
      }
    }

    &__footer {
      display: flex;
      max-width: 554px !important;
      justify-content: space-between;
      align-items: center;

      &-left-side {
        display: flex;
        justify-content: center;
        align-items: center;
      }
    }

    &__text {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      color: #2196f3;
      cursor: pointer;
    }

    &__test-text {
      font-family: 'Open Sans', sans-serif !important;
      font-size: 14px;
      font-weight: 600;
      font-stretch: normal;
      font-style: normal;
      line-height: 1.71;
      letter-spacing: normal;
      text-align: center;
      color: #757575 !important;
      opacity: 0.8;
    }
  }
}

::v-deep .theme--dark.v-btn:not(.v-btn--flat):not(.v-btn--text):not(.v-btn--outlined) {
  background-color: transparent;
}

::v-deep .new-integration__container.v-card {
  padding: 24px 0 0 96px !important;
}

::v-deep .v-list-item__content {
  padding: 0 !important;
}

::v-deep .v-input--selection-controls .v-input__slot > .v-label,
.v-input--selection-controls .v-radio > .v-label {
  font-family: 'Open Sans', sans-serif !important;
  left: 31px !important;
  font-size: 20px;
  font-weight: 600;
  font-stretch: normal;
  font-style: normal;
  line-height: 1.2;
  letter-spacing: normal;
  color: rgba(0, 0, 0, 0.87);
}
</style>
