import labels from '@/model/constants/labels'
import * as Validations from '@/utils/validations'

export const COMMON_CONSTANTS = {
  DISABLELOADER: -1,
  ENABLELOADER: 1,
  ERRORSNACKBARCOLOR: '#f56c6c',
  SUCCESSSNACKBARCOLOR: '#43a047',
  INFOSNACKBARCOLOR: '#2196f3',
  UPPERCASE: 'uppercase',
  LOWERCASE: 'lowercase',
  OUTLOOK: 'Outlook',
  DIAGNOSTIC: 'DiagnosticTool',
  PRIORITY_ITEMS: [
    { text: labels.VeryLow, value: 'VeryLow' },
    labels.Low,
    labels.Medium,
    labels.High,
    { text: labels.VeryHigh, value: 'VeryHigh' }
  ],
  STATUS_ITEMS: [
    { text: labels.Active, value: 1 },
    { text: labels.InActive, value: 0 }
  ],
  DEFAULT_EMAIL_RULES: [
    (v) => Validations.startsWithSpace(v, labels.CannotStartWithSpace),
    (v) => Validations.email(v, labels.InvalidEmailAddress),
    (v) => Validations.maxLength(v, 320, labels.getMaxLengthMessage(labels.Email, 320)),
    (v) => {
      if (Validations.email(v)) {
        return Validations.controlEmailLength(v) || labels.InvalidEmailAddress
      }
      return false
    }
  ],
  DEFAULT_URL_RULES: [
    (v) => Validations.startsWithSpace(v, labels.CannotStartWithSpace),
    (v) => Validations.url(v, labels.InvalidURL),
    (v) => Validations.maxLength(v, 5000, labels.getMaxLengthMessage(labels.URL, 5000)),
    (v) => Validations.noWhitespace(v, labels.InvalidURL)
  ],
  OPERATION_ITEMS: [
    { text: 'Create', value: 0 },
    { text: 'Update', value: 1 },
    { text: 'Delete', value: 2 },
    { text: 'CreateMany', value: 3 },
    { text: 'UpdateMany', value: 4 },
    { text: 'DeleteMany', value: 5 }
  ],
  CAMPAIGN_MANAGER_STATUS_ITEMS: [
    labels.Completed,
    labels.Running,
    labels.Idle,
    labels.Paused,
    labels.Cancelled
  ],
  FILTER_OPTIONS: ['Set as default filter', 'Restore default filter', 'Clear filters']
}

export const LABEL_STORE = {
  CREATEDATE: 'Date Created',
  CREATETIME: 'Date Created',
  FIRSTNAME: 'First Name',
  RELIABILITYPOINT: 'Reliability Point',
  LASTNAME: 'Last Name',
  LAUNCH_DATE: 'Launch Date',
  STATS: 'Stats',
  EMAIL: 'Email',
  HOSTNAME: 'Device',
  LASTSEEN: 'Last Seen',
  NAME: 'Name',
  ADDINVERSION: 'Version',
  STATUS: 'Status',
  DEPARTMENT: 'Department',
  PRIORITY: 'Priority',
  PROGRESS: 'Progress',
  SUBJECT: 'Subject',
  ATTACHMENTCOUNT: 'Attachment',
  REPORTEDBY: 'Reported By',
  RESULT: 'Result',
  INCIDENT: 'Incident',
  DETECTED: 'Detected',
  SOURCE: 'Source',
  ANALYSISSOURCE: 'Analysis Source',
  EXPIREDATE: 'Expiry Date',
  USERSTATUS: 'User Status',
  SCANSTATUS: 'Scan Status',
  FROM: 'From',
  TO: 'To',
  SCANTYPE: 'Service',
  DURATION: 'Duration',
  DESCRIPTION: 'Description',
  COMPANY: 'Company',
  DELIVERY: 'Delivery',
  COMPANYNAME: 'Company Name',
  APIKEY: 'API Key',
  DATECREATED: 'Date Created',
  RESULTTAG: 'Tags',
  SERVICE: 'Service',
  ISSENDFILEHASH: 'Hash Scan',
  ISSENDFILE: 'File Scan',
  DETAILS: 'Details',
  ANALYSISENGINE: 'Service',
  CREATEDBY: 'Created By',
  NO_INTEGRATIONS: 'You do not have any integrations',
  NO_EMAIL_TEMPLATES: 'You do not have any templates',
  NO_VISHING_TEMPLATES: 'You do not have any vishing templates',
  NO_RULES_CONFIGURED: 'You do not have any rules',
  NO_TARGET_GROUPS_DEFINED: 'You do not have any target groups',
  NO_TARGET_USER_ADDED: 'You do not have any users',
  NO_IP_ADDRESS_DEFINED: 'You do not have any IP Addresses',
  NO_NOTIFICATION_TEMPLATE_DEFINED: 'You do not have any notification templates',
  NO_AUDIT: 'You do not have any audit logs',
  NO_SCENARIO: 'You do not have any scenarios',
  NO_SCAN: 'You do not have any scan',
  NO_ATTACK_VECTOR: 'You do not have any attack vector',
  NO_SENT_ATTACK: 'You do not have any Sent Attacks',
  NO_ALLOW_LIST: 'You do not have any domain',
  INDUSTRYNAME: 'Industry',
  LICENSETYPENAME: 'License Type',
  NUMBEROFUSERS: 'User Limit',
  LICENSEENDDATE: 'Renewal Date',
  IPADDRESS: 'Ip Address',
  DIAGNOSTICTOOL: 'Diagnostic Tool',
  TYPE: 'Type',
  URL: 'URL',
  POSTTITLE: 'Post Title',
  USERS: 'Users',
  SMTPADDRESS: 'SMTP Address',
  AVAILABLEFOR: 'Available For',
  PROVIDER: 'Provider',
  ACCOUNTSID: 'Account SID',
  ROLE: 'Role',
  PHONENUMBER: 'Phone Number',
  STATUSNAME: 'Status',
  ADDINSTATUSNAME: 'Add-in Status',
  TYPENAME: 'Type',
  TITLE: 'Title',
  ROLENAME: 'Title',
  USERCOUNT: 'Users',
  JOBTITLE: 'Job Title',
  SERVERADDRESS: 'SMTP Address',
  USERNAME: 'User Name',
  NO_DATA: 'No Data',
  THREATS: 'Actual Threats',
  RELIABILITY: 'Reliability',
  RULENAME: 'Rule Name',
  UPLOADED_SUCCESSFULLY: 'Uploaded successfully',
  LOGID: 'Log ID',
  LOGDATE: 'Log Date',
  ENTITYID: 'Entity ID',
  ENTITYNAME: 'Entity Name',
  OPERATIOM: 'Operation',
  OLDVALUE: 'Old Value',
  NEWVALUE: 'New Value',
  IP: 'IP',
  USERAGENT: 'Browser User Agent',
  CHANGESET: 'Changed Set',
  INVESTIGATIONNAME: 'Investigation Name',
  TRIGGER: 'Trigger',
  FILEUPLOADED: 'File Uploaded',
  SENDERNAME: 'Sender Name',
  SENDERADDRESS: 'Sender Address',
  PERMISSIONS: 'You do not have any rules',
  ROLENAMEPERMISSION: 'Role Name',
  ROLEDESCRIPTION: 'Role Description'
}

export const PROPERTY_STORE = {
  RECIPIENT_TYPE: 'recipientType',
  INFOGRAPHIC_NAME: 'trainingName',
  MATERIAL_NAME: 'trainingName',
  SCREENSAVER_NAME: 'trainingName',
  BEHAVIOURS: 'behaviours',
  POSTER_NAME: 'trainingName',
  DATE_CREATED: 'dateCreated',
  VENDOR: 'vendor',
  AVAILABLE_FOR: 'availableForCompanyCount',
  LEARNING_PATH_NAME: 'trainingName',
  LANGUAGE: 'languageTypeName',
  EMAIL_TEMPLATE: 'emailTemplate',
  JUSTDIFFICULTY: 'difficulty',
  COMPLIANCE: 'compliances',
  HAS_TRAINING: 'hasTraining',
  QUISHING_SCENARIO_NAME: 'quishingScenarioName',
  LANDING_PAGE_TEMPLATE: 'landingPageTemplate',
  EMAIL_DELIVERY: 'emailDelivery',
  SCENARIO_COUNT: 'scenarioCount',
  ACTIVITYTYPE: 'activityType',
  AUDIENCE: 'audience',
  TRAINING_NAME: 'trainingName',
  START_DATE: 'startDate',
  TARGET_AUDIENCE: 'targetAudience',
  METHOD: 'method',
  TAGS: 'tags',
  COUNT: 'count',
  ENROLLED_BY: 'enrolledBy',
  TOEMAIL: 'toEmail',
  PHISHING_SCENARIO_NAME: 'phishingScenarioName',
  FREQUENCY_DESCRIPTION: 'frequencyDescription',
  OWNER: 'owner',
  FROMEMAIL: 'fromEmail',
  CATEGORY: 'category',
  DISTRIBUTED: 'distributed',
  CAMPAIGN_STATUS: 'campaignStatus',
  LANGUAGES: 'languages',
  STARTDATE: 'startDate',
  TARGET_USERS: 'targetUsers',
  ADDINSTATUSNAME: 'addInStatusName',
  PERIODTIME: 'periodTime',
  LASTOPENED: 'lastOpened',
  DATA: 'data',
  LAST_SENDING_DATE: 'lastSendingDate',
  LASTRUNTIME: 'lastRunTime',
  LAST_SENDING_STATUS: 'lastSendingStatus',
  DATECLICKED: 'dateClicked',
  SCENARIO: 'scenario',
  LASTCLICKED: 'lastClicked',
  BROWSER: 'browser',
  GEOLOCATION: 'geoLocation',
  EMAIL_SEND_DATE: 'emailSendDate',
  LAST_SUBMISSION: 'lastSubmission',
  PASSWORD_COMPLEXITY: 'passwordComplexity',
  TIMESCLICKED: 'timesClicked',
  ANALYSISENGINEPERMALINK: 'analysisEnginePermalink',
  CLIENTID: 'clientId',
  SMTP: 'smtp',
  TIMESOPENED: 'timesOpened',
  COMPANYID: 'companyId',
  TENANTUSERCOUNT: 'tenantUserCount',
  DIRECTORYID: 'directoryId',
  APPLICATIONID: 'applicationId',
  APPLICATIONSECRET: 'applicationSecret',
  ANALYSISENGINETYPE: 'analysisEngineType',
  ANALYSISENGINENAME: 'analysisEngineName',
  TIMES_SUBMISSION: 'timesSubmission',
  NAME: 'name',
  REASON: 'reason',
  PRIORITY: 'priority',
  USERNAME: 'userName',
  CREATEDATE: 'createDate',
  FIRSTNAME: 'firstName',
  CATEGORYNAME: 'categoryName',
  SCANTIME: 'scanTime',
  TYPNAME: 'typeName',
  TEMPLATETYPE: 'templateType',
  LASTNAME: 'lastName',
  RELIABILITY: 'reliability',
  THREATS: 'threats',
  MATCHCOUNT: 'matchCount',
  RULENAME: 'ruleName',
  EMAIL: 'email',
  DEPARTMENT: 'department',
  TITLE: 'title',
  SCHEDULE: 'schedule',
  DESCRIPTION: 'description',
  STATUS: 'status',
  DIAGNOSTICTOOL: 'diagnosticToolStatus',
  REPORTEREMAIL: 'reporterEmail',
  INTEGRATIONNAME: 'integrationName',
  RELIABILITYPOINT: 'reliabilityPoint',
  COMPANY: 'company',
  SUBJECT: 'subject',
  POSTTITLE: 'postTitle',
  COMMUNITYNAME: 'communityName',
  ATTACHMENTCOUNT: 'attachmentCount',
  REPORTEDBY: 'reportedBy',
  RESULT: 'result',
  HOSTNAME: 'hostName',
  COMMENTCOUNT: 'commentCount',
  LASTSEEN: 'lastSeen',
  ADDINVERSION: 'addInVersion',
  DELIVERY: 'delivery',
  DELIVERY_TYPE: 'deliveryType',
  COMPANYNAME: 'companyName',
  APIKEY: 'apiKey',
  DATECREATED: 'dateCreated',
  RESULTTAG: 'resultTag',
  SOURCE: 'source',
  SERVICE: 'service',
  ISSENDFILEHASH: 'isSendFileHash',
  ISSENDFILE: 'isSendFile',
  IPADDRESS: 'ipAddress',
  DETAILS: 'details',
  ANALYSISENGINE: 'analysisEngine',
  RESOURCEID: 'resourceId',
  ANALYSISSOURCE: 'source',
  CREATEDBY: 'createdBy',
  INDUSTRYNAME: 'industryName',
  LICENSETYPENAME: 'licenseTypeName',
  NUMBEROFUSERS: 'numberOfUsers',
  LICENSEENDDATE: 'licenseEndDate',
  TYPE: 'type',
  URL: 'url',
  USERS: 'users',
  SMTPADDRESS: 'serverAddress',
  AVAILABLEFOR: 'avaiableFor',
  PROVIDER: 'provider',
  ACCOUNTSID: 'accountSID',
  ROLE: 'role',
  PHONENUMBER: 'phoneNumber',
  ROLES: 'roles',
  STATUSNAME: 'statusName',
  CREATETIME: 'createTime',
  ROLENAME: 'roleName',
  USERCOUNT: 'userCount',
  TYPENAME: 'typeName',
  JOBTITLE: 'jobTitle',
  CLIENTNAME: 'clientName',
  PLATFORM: 'platform',
  LOGID: 'logId',
  LOGDATE: 'logDate',
  ENTITYID: 'entityResourceId',
  ENTITYNAME: 'entityName',
  OPERATIOM: 'operation',
  OLDVALUE: 'oldValue',
  NEWVALUE: 'newValue',
  IP: 'ip',
  USERAGENT: 'userAgent',
  USERID: 'userId',
  FILEUPLOADED: 'fileUploaded',
  NONE_SELECTED: 'None Selected',
  SENDERNAME: 'senderName',
  SENDERADDRESS: 'from',
  ROLEDESCRIPTION: 'roleDescription',
  PROXYADDRESS: 'proxySettings',
  PROXYNAME: 'Proxy Name',
  ADDRESS: 'address',
  PORT: 'port',
  AuthenticationTypeId: 'authenticationTypeId',
  AuthenticationTypeName: 'authenticationTypeName',
  ISDEFAULT: 'isDefault',
  TEMPLATENAME: 'TemplateName',
  DIFFICULTY: 'difficultyName',
  LASTLAUNCH: 'lastLaunch'
}

export const TABLE_SETTINGS_KEYS = {
  TRAINING_REPORT_USERS_TABLE: 'TrainingReportsUserTableSettings',
  TRAINING_REPORT_NON_TARGET_USERS_TABLE: 'TrainingReportsNonTargetUserTableSettings',
  TRAINING_LIBRARY_INFOGRAPHIC_TABLE: 'TrainingLibraryInfographicTableSettings',
  ENROLLMENTS_POSTER_LIST: 'EnrollmentsPosterListSettings',
  ENROLLMENTS_LEARNING_PATH_LIST: 'EnrollmentsLearningPathListSettings',
  TRAINING_LIBRARY_LEARNING_PATH_TABLE: 'TrainingLibraryLearningPathTableSettings',
  TRAINING_LIBRARY_SCREENSAVER_TABLE: 'TrainingLibraryScreensaverTableSettings',
  ENROLLMENTS_INFOGRAPHIC_LIST: 'EnrollmentsInfographicListSettings',
  ENROLLMENTS_TRAINING_LIST: 'EnrollmentsTrainingListSettings',
  ENROLLMENTS_ALL_TYPES_LIST: 'EnrollmentsAllTypesListSettings',
  SMSIHING_FREQUENCY_TABLE: 'SmishingFrequencyTableSettings',
  TRAINING_LIBRARY_POSTER_TABLE: 'TrainingLibraryPosterTableSettings',
  TRAINING_REPORT_OPENED_TABLE: 'TrainingReportOpenedTableSettings',
  TRAINING_LIBRARY_TRAINING_TABLE: 'TrainingLibraryTrainingTableSettings',
  TRAINING_REPORT_NON_TARGET_USERS_PROGRESS_TABLE:
    'TrainingReportNonTargetUserProgressTableSettings',
  TRAINING_REPORT_NON_TARGET_RESULTS_EXAM_RESULTS_TABLE:
    'TrainingReportNonTargetResultsExamResultsTableSettings',
  TRAINING_LIBRARY_ALL_TYPES_TABLE: 'TrainingLibraryAllTypesTableSettings',
  VISHING_REPORT_ANSWERED_TABLE: 'VishingReportAnsweredSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_SUBMITTED_MFA_TABLE:
    'QuishingCampaignManagerReportSubmittedMfaDataTableSettings',
  VISHING_REPORT_USERS_TABLE: 'VishingReportUsersTableSettings',
  QUISHING_DOMAINS: 'QuishingDomainsTableSettings',
  QUISHING_SCENARIOS: 'QuishingScenariosTableSettings',
  QUISHING_CAMPAIGN_MANAGER_ITEM_TABLE: 'QuishingCampaignManagerItemTableSettings',
  QUISHING_CAMPAIGN_MANAGER_PARENT_TABLE: 'QuishingCampaignManagerParentTableSettings',
  VISHING_REPORT_DIALED_TABLE: 'VishingReportDialedTableSettings',
  QUISHING_CAMPAIGN_MANAGER_FREQUENCY_TABLE: 'QuishingCampaignManagerFrequencyTableSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_SUBMITTED_TABLE:
    'QuishingCampaignManagerReportSubmittedDataTableSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_SENDING_REPORT_TABLE:
    'QuishingCampaignManagerReportSendingReportTableSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_PHISHING_REPORTER_TABLE:
    'QuishingCampaignManagerReportPhishingReporterTableSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_ATTACHMENT_TABLE:
    'QuishingCampaignManagerReportAttachmentTableSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_CLICKED_TABLE:
    'QuishingCampaignManagerReportClickedTableSettings',
  QUISHING_EMAIL_TEMPLATES: 'QuishingEmailTemplatesTableSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_NO_RESPONSE_TABLE:
    'QuishingCampaignManagerReportNoResponseTableSettings',
  QUISHING_LANDING_PAGES: 'QuishingLandingPagesTableSettings',
  QUISHING_CAMPAIGN_MANAGER_REPORT_OPENED_TABLE: 'QuishingCampaignManagerReportOpenedTableSettings',
  QUISHING_DNSSERVICELIST: 'QuishingDNSServiceListTableSettings',
  VISHING_REPORT_NO_RESPONSE_TABLE: 'VishingReportNoResponseTableSettings',
  CAMPAIGN_MANAGER_FREQUENCY_TABLE: 'CampaignManagerFrequencyTableSettings',
  TRASH_LIST: 'TrashListTableSettings',
  DIRECT_EMAIL_CREATION: 'DirectEmailCreationTableSettings',
  TRAINING_REPORT_CLICKED_TABLE: 'TrainingReportClickedTableSettings',
  TRAINING_REPORT_PROGRESS_TABLE: 'TrainingReportProgressTableSettings',
  TRAINING_REPORT_EXAM_RESULTS_TABLE: 'TrainingReportExamResultsTableSettings',
  TRAINING_REPORT_NO_RESPONSE_TABLE: 'TrainingReportNoResponseTableSettings',
  TRAINING_REPORT_SENDING_REPORT_TABLE: 'TrainingReportSendingReportTableSettings',
  REPORTED_EMAIL: 'ReportedEmailTableSettings',
  CAMPAIGN_MANAGER_REPORT_SENDING_REPORT_TABLE: 'CampaignManagerReportSendingReportTableSettings',
  CAMPAIGN_MANAGER_REPORT_OPENED_TABLE: 'CampaignManagerReportOpenedTableSettings',
  CERTIFICATES_LIST: 'CertificatesListTableSettings',
  CAMPAIGN_MANAGER_REPORT_PHISHING_REPORTER_TABLE:
    'CampaignManagerReportPhishingReportTableSettings',
  CAMPAIGN_MANAGER_REPORT_ATTACHMENT_TABLE: 'CampaignManagerReportAttachmentTableSettings',
  SCIM_SETTINGS_TABLE: 'SCIM_SETTINGS_TABLE',
  CAMPAIGN_MANAGER_REPORT_NO_RESPONSE_TABLE: 'CampaignManagerReportNoResponseTableSettings',
  CAMPAIGN_MANAGER_REPORT_CLICKED_TABLE: 'CampaignManagerReportClickedTableSettings',
  CAMPAIGN_MANAGER_REPORTS_TABLE: 'CampaignManagerReportsTableSettings',
  CAMPAIGN_MANAGER_PARENT_TABLE: 'CampaignManagerParentTableTableSettings',
  CALLBACK_CAMPAIGN_MANAGER_PARENT_TABLE: 'CallbackCampaignManagerParentTableTableSettings',
  CAMPAIGN_MANAGER_REPORT_SUBMITTED_TABLE: 'CampaignManagerReportSubmittedDataTableSettings',
  CAMPAIGN_MANAGER_REPORT_SUBMITTED_MFA_TABLE: 'CampaignManagerReportSubmittedMfaDataTableSettings',
  CAMPAIGN_REPORTS: 'CampaignReportsTableSettings',
  CAMPAIGN_MANAGER_ITEM_TABLE: 'CampaignManagerItemTable',
  CLUSTERED_REPORTED_EMAIL: 'ClusteredReportedEmailTableSettings',
  INVESTIGATIONS: 'InvestigationsTableSettings',
  ENROLLMENTS_LIST: 'EnrollmentsTableSettings',
  INVESTIGATION_DETAILS_TARGET_USER: 'InvestigationDetailsTargetUserTableSettings',
  INVESTIGATION_DETAILS_LIST: 'InvestigationDetailsListTableSettings',
  INTEGRATION: 'IntegrationTableSettings',
  SIEMIntegration: 'SiemIntegrationTableSettings',
  PLAYBOOK: 'PlaybookTableSettings',
  MAILCONFIGURATION: 'MailConfigurationTableSettings',
  PHISHINGREPORTER: 'PhishingReporterTableSettings',
  TARGET_USERS_VIEW_USER_GROUPS: 'targetUsersViewUserGroupsTableSettings',
  TARGET_USERS_PEOPLE: 'TargetUsersPeopleTableSettings',
  COMPANY_LIST: 'CompanyListTableSettings',
  COMPANY_GROUP_LIST: 'CompanyGroupListTableSettings',
  COMPANY_GROUP_DETAILS: 'CompanyGroupDetailsTableSettings',
  SMTP_SETTINGS: 'SmtpSettingsTableSettings',
  TRAINING_LIST: 'TrainingListTableSettings',
  NOTIFICATION_TEMPLATE: 'NotificationTemplateTableSettings',
  REST_API: 'RestApiTableSettings',
  SYSTEM_USERS_PEOPLE: 'SystemUsersPeopleTableSettings',
  SYSTEM_USERS_ROLES: 'SystemUsersRolesSettings',
  AUDIT: 'AuditTableSettings',
  TARGET_USERS_GROUPS: 'TargetUsersGroupsTableSettings',
  TARGET_USERS_GROUP_USERS: 'TargetUsersGroupUsersSettings',
  SAML_SETTINGS: 'SamlSettingsTableSettings',
  PROXY_SETTINGS: 'ProxySettingsTableSettings',
  CALLBACK_EMAIL_TEMPLATES: 'CallbackEmailTemplatesTableSettings',
  CALLBACK_SETTINGS: 'CallbackSettingsTableSettings',
  EMAILTEMPLATES: 'EmailTemplatesTableSettings',
  VISHINGTEMPLATES: 'VishingTemplatesTableSettings',
  CALLBACK_TEMPLATES: 'CallbackTemplatesTableSettings',
  VISHING_CAMPAIGN_MANAGER: 'VishingCampaignManagerSettings',
  SANDBOX: 'Sandbox',
  SANDBOXSTATS: 'SandboxStats',
  DNSSERVICELIST: 'DNSServiceListTableSettingsKey',
  DOMAINS: 'DomainsListTableSettingsKey',
  LANDINGPAGES: 'LandingPagesTableSettingsKey',
  SCENARIOS: 'Scenarios',
  CALLBACK_SCENARIOS: 'CallbackScenarios',
  SMISHING_SCENARIOS: 'SmishingScenarios',
  SMISHING_TEMPLATES: 'SmishingTemplates',
  SMISHING_LANDING_PAGES: 'SmishingLandingPages',
  LASTLAUNCH: 'lastLaunch',
  ETS_QUICK_SCAN_TABLE: 'EtsQuickScanSettings',
  ETS_ATTACK_VECTOR_TABLE: 'EtsAttackVectorSettings',
  ETS_REPORT_SENT_ATTACK_TABLE: 'EtsReportSentAttackSettings',
  THREATS_INTELLIGENCE_TABLE: 'ThreatIntelligenceSettings',
  ALLOW_LIST_TABLE: 'AllowListSettings'
}

export function getStoreValue(key, type) {
  key = key.trim().toUpperCase()
  let value = LABEL_STORE[key]
  if (type === COMMON_CONSTANTS.UPPERCASE) {
    value = value.toUpperCase()
  }
  if (type === COMMON_CONSTANTS.LOWERCASE) {
    value = value.toLowerCase()
  }
  return value
}

export const columnStandards = [
  { property: 'firstName', width: '140' },
  { property: 'lastName', width: '200' },
  { property: 'email', width: '260' },
  { property: 'department', width: '150' },
  { property: 'jobTitle', width: '140' },
  { property: 'companyName', width: '200' },
  { property: 'description', width: '340' },
  { property: 'subject', width: '200' },
  { property: 'url', width: '260' },
  { property: 'language', width: '140' },
  { property: 'createTime', width: '160' },
  { property: 'utcTime', width: '160' },
  { property: 'expireDate', width: '160' },
  { property: 'lastSeen', width: '160' },
  { property: 'licenseEndDate', width: '160' },
  { property: 'name', width: '260' }
]

export const GrapesS3Options = {
  accessKeyId: '<AWS Access key Id>',
  secretAccessKey: '<Aws secret access key>',
  sessionToken: '<AWS Sessions Token>',
  bucketName: '<AWS S3 Bucket Name>',
  prefix: '<Folder Name in s3 bucket.>'
}

export const COMMON_PROPS = {
  AVAILABLEFOR: {
    placeholder: labels.MakeAvailableForPlaceholder,
    valueFormat: 'object',
    clearOnSelect: true,
    defaultOptions: true,
    disableBranchNodes: true,
    multiple: true,
    searchNexted: true,
    showCount: true
  }
}

export const COMMON_SNACKBAR = {
  show: true,
  color: COMMON_CONSTANTS.SUCCESSSNACKBARCOLOR,
  icon: 'mdi-check-circle'
}

export const DEFAULT_SEARCH_CONTAINER_KEYS = {
  TRAINING_REPORT_USERS_TABLE: 'TrainingReportUserTable',
  TRAINING_LIBRARY_LEARNING_PATH_TABLE: 'TrainingLibraryLearningPathTable',
  TRAINING_LIBRARY_INFOGRAPHIC_TABLE: 'TrainingLibraryInfographicTable',
  ENROLLMENTS_POSTER_LIST: 'EnrollmentsPosterList',
  TRAINING_LIBRARY_TRAINING_TABLE: 'TrainingLibraryTrainingTable',
  ENROLLMENTS_INFOGRAPHIC_LIST: 'EnrollmentsInfographicList',
  ENROLLMENTS_TRAINING_LIST: 'EnrollmentsTrainingList',
  ENROLLMENTS_LEARNING_PATH_LIST: 'EnrollmentsLearningPathList',
  ENROLLMENTS_ALL_TYPES_LIST: 'EnrollmentsAllTypesList',
  TRAINING_LIBRARY_POSTER_TABLE: 'TrainingLibraryPosterTable',
  TRAINING_REPORT_NON_TARGET_USERS_TABLE: 'TrainingReportNonTargetUserTable',
  TRAINING_LIBRARY_SCREENSAVER_TABLE: 'TrainingLibraryScreensaverTable',
  TRAINING_REPORT_NON_TARGET_USERS_PROGRESS_TABLE: 'TrainingReportNonTargetUserProgressTable',
  TRAINING_REPORT_OPENED_TABLE: 'TrainingReportOpenedTable',
  SMSIHING_FREQUENCY_TABLE: 'SmishingFrequencyTableSearchContainerKeys',
  TRAINING_REPORT_NON_TARGET_RESULTS_EXAM_RESULTS_TABLE:
    'TrainingReportNonTargetResultsExamResultsTable',
  VISHING_REPORT_USERS_TABLE: 'VishingReportUsersTable',
  VISHING_REPORT_ANSWERED_TABLE: 'VishingReportAnsweredTable',
  QUISHING_DOMAINS: 'QuishingDomainsTableContainerKeys',
  QUISHING_SCENARIOS: 'QuishingScenariosTableContainerKeys',
  TRAINING_LIBRARY_ALL_TYPES_TABLE: 'TrainingLibraryAllTypesTable',
  QUISHING_DNSSERVICELIST: 'QuishingDNSServiceListTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_REPORT_SUBMITTED_MFA_TABLE:
    'QuishingCampaignManagerReportSubmittedMfaDataTableSearchKeys',
  VISHING_REPORT_DIALED_TABLE: 'VishingReportDialedTable',
  QUISHING_CAMPAIGN_MANAGER_REPORT_SUBMITTED_TABLE:
    'QuishingCampaignManagerReportSubmittedDataTableSearchKeys',
  QUISHING_CAMPAIGN_MANAGER_REPORT_SENDING_REPORT_TABLE:
    'QuishingCampaignManagerReportSendingReportTable',
  QUISHING_LANDING_PAGES: 'QuishingLandingPagesTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_FREQUENCY_TABLE: 'QuishingCampaignManagerFrequencyTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_REPORT_PHISHING_REPORTER_TABLE:
    'QuishingCampaignManagerReportPhishingReporterTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_REPORT_ATTACHMENT_TABLE:
    'QuishingCampaignManagerReportAttachmentTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_REPORT_CLICKED_TABLE:
    'QuishingCampaignManagerReportClickedTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_REPORT_NO_RESPONSE_TABLE:
    'QuishingCampaignManagerReportNoResponseTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_REPORT_OPENED_TABLE:
    'QuishingCampaignManagerReportOpenedTableContainerKeys',
  QUISHING_CAMPAIGN_MANAGER_ITEM_TABLE: 'QuishingCampaignManagerItemTableContainerKeys',
  VISHING_REPORT_NO_RESPONSE_TABLE: 'VishingReportNoResponseTable',
  QUISHING_EMAIL_TEMPLATES: 'QuishingEmailTemplatesTableContainerKeys',
  CAMPAIGN_MANAGER_FREQUENCY_TABLE: 'CampaignManagerFrequencyTableContainerKeys',
  TRASH_LIST: 'TrashListTable',
  DIRECT_EMAIL_CREATION: 'DirectEmailCreationTable',
  TRAINING_REPORT_CLICKED_TABLE: 'TrainingReportClickedTable',
  TRAINING_REPORT_PROGRESS_TABLE: 'TrainingReportProgressTable',
  TRAINING_REPORT_EXAM_RESULTS_TABLE: 'TrainingReportExamResultsTable',
  TRAINING_REPORT_NO_RESPONSE_TABLE: 'TrainingReportNoResponseTable',
  TRAINING_REPORT_SENDING_REPORT_TABLE: 'TrainingReportSendingReportTable',
  CAMPAIGN_MANAGER_PARENT_TABLE: 'CampaignManagerParentTable',
  CALLBACK_CAMPAIGN_MANAGER_PARENT_TABLE: 'CallbackCampaignManagerParentTable',
  QUISHING_CAMPAIGN_MANAGER_PARENT_TABLE: 'QuishingCampaignManagerParentTable',
  CAMPAIGN_MANAGER_ITEM_TABLE: 'CampaignManagerItemTable',
  CAMPAIGN_MANAGER_REPORTS_TABLE: 'CampaignManagerReportsTableSearchKeys',
  CERTIFICATES_LIST: 'CertificatesListTableSearchKeys',
  CAMPAIGN_MANAGER_REPORT_SENDING_REPORT_TABLE: 'CampaignManagerReportSendingReportTableSearchKeys',
  CAMPAIGN_MANAGER_REPORT_SUBMITTED_TABLE: 'CampaignManagerReportSubmittedDataTableSearchKeys',
  CAMPAIGN_MANAGER_REPORT_SUBMITTED_MFA_TABLE:
    'CampaignManagerReportSubmittedMfaDataTableSearchKeys',
  CAMPAIGN_MANAGER_REPORT_ATTACHMENT_TABLE: 'CampaignManagerReportAttachmentDataTableSearchKeys',
  ENROLLMENTS_LIST: 'EnrollmentListSearchKeys',
  PHISHING_REPORTER: 'PhishingReporter',
  SMTP_SETTINGS: 'SmtpSettings',
  SCIM_SETTINGS: 'SCIMSettingsDataTableSearchKeys',
  PERMISSION: 'PERMISSION',
  SIEM_INTEGRATION: 'SiemIntegrationSearchKeys',
  NOTIFICATION_TEMPLATE: 'NotificationTemplate',
  REST_API: 'RestApiSearchKeys',
  TRAINING_LIST: 'TrainingListSearchKeys',
  CAMPAIGN_REPORTS: 'CampaignReportsSearchKeys',
  CAMPAIGN_MANAGER_REPORT_OPENED_TABLE: 'CampaignManagerReportOpenedTableSearchKeys',
  CAMPAIGN_MANAGER_REPORT_PHISHING_REPORTER_TABLE:
    'CampaignManagerReportPhishingReporterTableSearchKeys',
  CAMPAIGN_MANAGER_REPORT_NO_RESPONSE_TABLE: 'CampaignManagerReportNoResponseTableSearchKeys',
  CAMPAIGN_MANAGER_REPORT_CLICKED_TABLE: 'CampaignManagerReportClickedTableSearchKeys',
  REPORTED_EMAIL: 'ReportedEmail',
  REPORTED_EMAIL_CLUSTERED: 'ReportedEmailClustered',
  INVESTIGATIONS: 'Investigations',
  TARGETUSERS: 'TargetUsers',
  TARGETUSERSGROUP: 'TargetUsersGroup',
  TARGETGROUPUSERSTABLE: 'TargetGroupUsersTable',
  SYSTEMUSERSPEOPLE: 'SystemUsersPeople',
  AUDIT: 'AuditSearchKeys',
  INTEGRATIONS: 'Integrations',
  PLAYBOOKRULES: 'PlaybookRules',
  MAILCONFIG: 'MailConfig',
  COMPANY_LIST: 'CompanyList',
  ADD_COMPANY_LIST: 'AddCompanyList',
  COMPANY_GROUP_LIST: 'CompanyGroupList',
  COMPANY_GROUP_DETAILS: 'CompanyGroupDetails',
  INVESTIGATIONSFOLDER: 'InvestigationsFolder',
  INVESTIGATIONSTARGETUSERS: 'InvestigationsTargetUsers',
  SAMLSETTINGS: 'SamlSettings',
  PROXY_SETTINGS: 'ProxySettings',
  CALLBACK_EMAIL_TEMPLATES: 'CallbackEmailTemplatesSearchContainer',
  CALLBACK_SETTINGS: 'CallbackSettingsSearchContainer',
  EMAILTEMPLATES: 'EmailTemplatesSearchContainer',
  VISHINGTEMPLATES: 'VishingTemplatesSearchContainer',
  CALLBACK_TEMPLATES: 'CallbackTemplatesSearchContainer',
  VISHING_CAMPAIGN_MANAGER: 'VishingCampaignManagerSearchContainer',
  SANDBOX: 'Sandbox',
  sandbox: 'Sandbox',
  SANDBOXSTATS: 'SandboxStatsSearchContainerKeys',
  DNSSERVICELIST: 'DNSServiceListSearchContainerKeys',
  TARGETUSERSVIEWUSERGROUPS: 'TargetUsersViewUsersGroups',
  DOMAINS: 'DomainsSearchContainerKeys',
  LANDINGPAGES: 'LandingPagesSearchContainerKeys',
  SCENARIOS: 'ScenariosSearchKeys',
  CALLBACK_SCENARIOS: 'CallbackScenariosSearchKeys',
  SMISHING_SCENARIOS: 'SmishingScenariosSearchKeys',
  SMISHING_TEMPLATES: 'SmishingTemplatesSearchKeys',
  SMISHING_LANDING_PAGES: 'SmishingLandingPagesSearchKeys',
  ETS_QUICK_SCAN_TABLE: 'EtsQuickScanKeys',
  ETS_ATTACK_VECTOR_TABLE: 'EtsAttackVectorKeys',
  ETS_REPORT_SENT_ATTACK_TABLE: 'EtsReportSentAttackKeys',
  THREATS_INTELLIGENCE: 'ThreatIntelligenceList',
  ALLOW_LIST_TABLE: 'AllowListKeys'
}

export const INTEGRATION_TYPES = {
  ANYRUN: 'AnyRun',
  VMRAY: 'VMRay',
  FORTINET: 'FortiSandbox',
  VIRUSTOTAL: 'VirusTotal',
  IBMXFORCE: 'IBM X-Force',
  GOOGLESAFEBROWSER: 'Google Safe Browsing',
  SPAMHOUSE: 'Zen Spamhaus',
  CUSTOMINTEGRATION: 'Cross Company Integration',
  ROKSIT: 'Cyber X-Ray',
  CyberXRay: 'Cyber X-Ray',
  GOOGLEWEBRISK: 'Google Web Risk',
  OPSWAT: 'OPSWAT'
}
export const INTEGRATION_LABELS = {
  ANYRUN: 'AnyRun',
  VMRAY: 'VMRay',
  FORTINET: 'FortiSandbox',
  VIRUSTOTAL: 'VirusTotal',
  IBMXFORCE: 'IBM X-Force',
  CUSTOMINTEGRATION: 'Cross Company Integration',
  SPAMHOUSE: 'SPAMHOUSE',
  GOOGLESAFEBROWSER: ' Google Safe Browser',
  CyberXRay: 'Cyber X-Ray'
}
