export const labels = {
  getMaxLengthMessage(val = '', length = 64) {
    return `${val} cannot exceed ${length} characters`
  },
  getMinLengthMessage(val = '', length = 3) {
    return `${val} must have at least ${length} characters`
  },
  FastLaunch: 'Fast Launch',
  ZoneID: 'Zone ID',
  ApiKey: 'API Key',
  Completed: 'Completed',
  PhishingScenarios: 'Phishing Scenarios',
  LandingPage: 'Landing Page',
  SendingLimit: 'Sending Limit',
  OtherSettings: 'Other Settings',
  TestingConnection: 'Testing Connection',
  SendingLimitSub: 'Number of emails to be sent in each batch',
  Smtp: 'SMTP',
  Distribution: 'Distribution',
  DistributionSub: 'Send emails with selected intervals or over a specified time period',
  CustomizeSmtpForEachCompany: 'Customize SMTP For Each Company',
  CustomizeSmtpForEachCompanySub: 'Set SMTP configuration for each company',
  SmtpSub: 'Select SMTP configuration for this campaign',
  Duration: 'Duration',
  DurationSub: 'Select the time period you want to keep this campaign active',
  PhishingScenariosSub: 'Select scenario to use in this campaign',
  PhishingCampaignInfo: 'Phishing Campaign Info',
  PhishingCampaignInfoSub: 'Enter basic information about this campaign',
  AdvancedSettingsSub: 'Select advanced settings',
  CampaignSummarySub: 'Preview what this campaign will look like',
  CloseAdvancedSearch: 'Close Advanced Search',
  OpenAdvancedSearch: 'Open Advanced Search',
  TemplatePreview: 'Template Preview',
  Running: 'Running',
  ScheduleSub: 'Select the start time of this campaign',
  Idle: 'Idle',
  TargetGroups: 'Target Groups',
  TargetGroupsSub: 'Select target groups to send this phishing email',
  InstancesOfCampaign: 'Instances Of Campaign',
  Start: 'Start',
  Stop: 'Stop',
  Paused: 'Paused',
  Cancelled: 'Cancelled',
  CampaignName: 'Campaign Name',
  Duplicate: 'Duplicate',
  CampaignInfo: 'Campaign Info',
  Schedule: 'Schedule',
  CampaignSummary: 'Campaign Summary',
  Launch: 'Launch',
  Resume: 'Resume',
  Pause: 'Pause',
  DateCreated: 'Date Created',
  AnalysisDate: 'Analysis Date',
  LastLaunch: 'Last Launch',
  InvalidURLS: 'There are invalid URLs',
  AddCompaniesToCompanyGroupSubtitle: 'Select companies to add',
  CompanyGroupNameSecondLower: 'Company group name',
  BatchImport: 'Batch Import',
  BatchImportPopupSubtitle: 'Import multiple domains separated by line-break or comma',
  BatchImportPopupIpAddressSubtitle: 'Import multiple IP address separated by line-break or comma',
  CommunityName: 'Community Name',
  CompanyId: 'Company ID',
  CompanyAdmin: 'Company Admin',
  CertificateName: 'Certificate Name',
  NoTargetUserGroups: 'You do not have entered any groups',
  Default: 'Default',
  SamlName: 'SAML Name',
  AllowedDomains: 'Allowed Domains',
  CopyToClipboard: 'Copy to Clipboard',
  Attachments: 'Attachments',
  AttachmentsSubtitle: 'Exclude email attachments by file type from analysis',
  SamlSettings: 'SAML Settings',
  IdPEntityID: 'Idp Entity ID',
  TenantUserCount: 'Tenant Users',
  SelectEmailTemplateTitle: 'Select Email Template',
  Skip: 'Skip',
  YesConfigure: 'Yes, Configure',
  SamlConfigurationFor: 'SAML Configuration For',
  TestConnection: 'Test Connection',
  SamlDomainSubLabel: 'Include domains to be used with this configuration',
  SamlModalBodyTitle: 'New SAML Configuration',
  SamlMetadataSubLabel: 'Enter information from your identity provider',
  SamlModalBodyEditTitle: 'Edit SAML Configuration',
  SamlModalBodySubTitle: 'Set new SAML configuration',
  SamlModalBodyEditSubTitle: 'Set edit SAML configuration',
  SamlSettingsSubHeader: 'Manage SAML Configurations',
  EmptySamlTableSub: 'Create your first SAML configuration',
  EmptyTargetGroup: 'You do not have any Target Groups',
  SamlAddButtonTooltip: 'Add Saml Setting',
  SAMLIdpTargetUrl: 'IdP SSO Target URL',
  SAMLIdpCert: 'IdP Cert Fingerprint',
  EnableSAMLSSO: 'Enable SAML SSO',
  NewCompanyQuickSetup: 'New Company Quick Setup',
  EntityId: 'Entity ID',
  SSOEnabled: 'SSO Enabled',
  Metadata: 'Metadata',
  SAMLSettingName: 'SAML Name',
  SAMLSettingNameSubtitle: 'Name this SAML configuration',
  Regex: 'Regex',
  ConditionsSubHeader:
    'Define conditions to filter reported emails in order to take actions. Use conditional expressions “and” and “or” to create required criteria. You can add conditions sets for even more complicated conditions',
  ClientName: 'Client Name',
  ClientNameSecondLower: 'Client name',
  SSOSignInURL: 'SSO Sign-in URL',
  SSOSignOutURL: 'SSO Sign-out URL',
  SSOCallbackURL: 'SSO Callback URL',
  MetadataUrl: 'Metadata URL',
  BypassSSOLoginURL: 'Bypass SSO Login URL',
  NextSteps: 'Next Steps',
  EditClient: 'Edit Client',
  NewClient: 'New Client',
  URLS: 'URLs',
  URLSSubtitle: 'Exclude URLs that are found inside email’s body from analysis',
  IPAddressesSubtitle: 'Exclude IP adresses that are found inside email’s body from analysis',
  WhiteLabelingSubTitle:
    'Change branding and white labeling settings. Changes logos, urls, email addresses globally.  Skip to use system settings.',
  WhiteListingSubTitle:
    'Allow emails to be recieved without being filtered by antispam and other applications',
  CreateFirstSystemUser: 'Create First System User',
  CreateFirstSystemUserSubTitle:
    'Create the first user for this new company. You skip this step for now.',
  Keyword: 'Keyword',
  Notes: 'Notes',
  ConfigureNewCompanyTitle: 'Configure New Company?',
  SendWhitelistingDirections: 'Send Whitelisting Directions',
  SendWhitelistingDirectionsSubTitle: 'Send an email to customer with whitelisting directions',
  ReleaseInformation: 'Release Information',
  SAMLDeletePopupBody: 'This SAML setting will be deleted. All data will be lost.',
  ReleaseInformationSubTitle:
    'Show version and release notes link at the bottom of the navigation menu',
  CompanyNameSecondLower: 'Company name',
  SenderName: 'Sender name',
  Title: 'Title',
  IpAddresses: 'IP Addresses',
  ReAnalyze: 'Re-analyze',
  SHA512: 'SHA512',
  SHA1: 'SHA1',
  SHA256: 'SHA256',
  Extension: 'Extension',
  MD5: 'MD5',
  URL: 'Url',
  Cancel: 'CANCEL',
  Confirm: 'CONFIRM',
  NotInstalled: 'Not Installed',
  ServiceProvider: 'Service Provider',
  CannotStartWithSpace: 'Cannot start with space',
  Save: 'SAVE',
  Delete: 'Delete',
  Next: 'NEXT',
  RestApi: 'Rest Api',
  IntegrationType: 'Integration Type',
  Reason: 'Reason',
  OK: 'OK',
  Prev: 'PREV',
  Back: 'BACK',
  InvalidPhoneNumber: 'Invalid phone number',
  Email: 'Email Address',
  JustEmail: 'Email',
  FromName: 'From Name',
  EmptySamlTable: 'You do not have any SAML configuration',
  EmptyCampaignManager: 'You do not have any Campaign Manager',
  EmptySamlTableButton: 'Create a new SAML configuration',
  CreateNewNotificationTemplate: 'Create New Notification Template',
  EditNewNotificationTemplate: 'Edit Notification Template',
  NextStepsSubTitle: 'A few more suggestions',
  SaveAndContinue: 'save and continue',
  Name: 'Name',
  Description: 'Description',
  Low: 'Low',
  High: 'High',
  VeryHigh: 'Very High',
  VeryLow: 'Very Low',
  Category: 'Category',
  TemplateType: 'Template Type',
  InvalidExtension: 'Invalid extension',
  GenerateClientCred: 'GENERATE Client Credentials',
  EmailSubject: 'Email Subject',
  Industry: 'Industry',
  Result: 'Result',
  Size: 'Size',
  UserNameOrEmailAddress: 'User Name or Email Address',
  Medium: 'Medium',
  Country: 'Country',
  TemplateName: 'Template Name',
  UserName: 'User Name',
  Department: 'Department',
  CreateTime: 'Date Created',
  Address: 'Address',
  WebsiteUrl: 'Website URL',
  FirstName: 'First Name',
  FirstNameSecondLower: 'First name',
  LastName: 'Last Name',
  LastNameSecondLower: 'Last name',
  CompanyName: 'Company Name',
  Password: 'Password',
  CompanyGroup: 'Company Group',
  GoogleWorkSpaceTitle: 'Google Workspace Mail Configuration',
  GoogleWorkSpaceSubTitle: 'Google Workspace email configuration. Learn',
  HowToCredJSON: 'how to get a credential JSON',
  Closed: 'Closed',
  User: 'User',
  Users: 'Users',
  Open: 'Open',
  Matches: 'match(es)',
  IpAddress: 'Ip Address',
  InvalidDomainName: 'Invalid domain name',
  EmailAddress: 'Email Address',
  StopOngoingInvestigation: 'Stop Ongoing Investigation',
  DoYouWantToStopInvestigation: 'Do you want to stop this investigation?',
  OnceYouStoppedInvestigation: 'Once stopped, you cannot resume this investigation',
  Setting: 'Setting',
  Settings: 'Settings',
  Latest: 'Latest',
  Release: 'Release',
  Active: 'Active',
  InActive: 'Inactive',
  AddIn: 'Add-in',
  ReportedEmailTrends: 'Reported Email Trends',
  General: 'General',
  NoUsersToAdd: 'No users to add',
  Brand: 'Brand',
  BrandName: 'Brand Name',
  BrandNamePlaceHolder: 'Enter Company Name',
  BrandNameSubTitle: 'Your users and customers will see the platform under this brand name',
  MainDomain: 'Main Domain',
  Domain: 'Domain',
  AdvancedSettings: 'Advanced Settings',
  AdvancedSettingsSubTitle:
    'You can exclude domains, URLs, IP addresses , attachment extensions from the analysis process',
  MainDomainSubTitle: 'Your company’s web domain',
  MainDomainPlaceHolder: 'Enter domain',
  MainLogo: 'Main Logo',
  MainLogoSubTitle: 'Appears at top of the main menu as platform logo',
  Reporters: 'Reporters',
  TopRules: 'Top Rules',
  MatchingIncidents: 'Matching Incidents',
  Installation: 'Installation',
  Configuration: 'Configuration',
  MostTriggeredPlaybookRules: 'Most triggered Playbook rules',
  And: 'and',
  Guide: 'Guide',
  Status: 'Status',
  NoRulesConfigured: 'You do not have any rules',
  CreateNewRule: 'CREATE NEW RULE',
  New: 'New',
  Playbook: 'Playbook',
  NoMatchEmptyText: 'No Match',
  Actions: 'Actions',
  RuleInformation: 'Rule Information',
  EnterRuleInformation: 'Enter rule information',
  EmptyTopRulesWidget: 'You do not have any top rules',
  EmptyTopPostWidget: 'You do not have any top posts',
  EmptyTargetUsersPeople: 'You do not have any target users',
  EmptyTargetUsersPeopleSubCampaignManager: 'Go to Company>Target Users to import target users',
  EmptyTargetUsersPeopleSub: 'Create your first target user',
  EmptyRecentlyPostedThreats: 'You do not have any recently posted threats',
  EmptyRecentlyReportedIncidents: 'You do not have any reported incidents',
  EmptyMatchingIncidents: 'You do not have any matching incidents',
  EmptyReportedEmailText: 'You do not have any reported mails',
  EmptyCompany: 'You do not have any companies',
  EmptyReportedEmailSubText:
    'Emails that are reported by your users via Phishing Reporter add-in analysed and listed here',
  Community: 'Community',
  AddAnIntegration: 'ADD AN INTEGRATION',
  Logo: 'Logo',
  CompanyLogo: 'Company Logo',
  Close: 'Close',
  RuleName: 'Rule Name',
  MostRecentInvestigations: 'Most recent investigations',
  Heading: 'Heading',
  DialogBox: 'Dialog Box',
  InAnalysis: 'In Analysis',
  Edit: 'Edit',
  PreviewEmail: 'Preview Email',
  TargetUsers: 'Target Users',
  DefineTags: 'Define tags for the rule',
  PhishingReporterSettings: 'PHISHING REPORTER SETTINGS',
  Details: 'Details',
  Priority: 'Priority',
  Tags: 'Tags',
  Investigate: 'Investigate',
  ReportedEmails: 'Reported Emails',
  SummaryOfReportedEmails: 'Summary of emails reported for analysis',
  IncidentClusters: 'Incident Clusters',
  RecentlyPostedThreats: 'Recently Posted Threats',
  RecentlyReportedIncidents: 'Recently Reported Incidents',
  Offline: 'Offline',
  Conditions: 'Conditions',
  RecentInvestigations: 'Recent Investigations',
  InvestigationName: 'Investigation Name',
  RoiSummary: 'ROI Summary',
  Online: 'Online',
  PhishingReporter: 'Phishing Reporter',
  InstallNow: 'Install Now',
  NoAddInInstalled: 'No add-ins installed',
  Required: 'Required',
  NoTargetGroupUserAdded: 'There is no user in this group',
  AlertBox: 'Alertbox',
  CurrentlyOnline: 'Currently Online',
  Subject: 'Subject',
  Saved: 'Saved',
  NoEmailAnalysed: 'You haven’t analysed any emails',
  Money: 'Money',
  Auto: 'Auto',
  Investigations: 'Investigations',
  Manual: 'Manual',
  FoundHarmful: 'Found harmful',
  IncidentAnalysis: 'Incident Analysis',
  Progress: 'Progress',
  InvalidEmailAddress: 'Invalid email address',
  SaveAndDownload: 'Save and Download',
  SaveChanges: 'Save Changes',
  NoInvestigationStarted: 'You do not have any investigations',
  NoInvestigation: 'You do not have any investigations',
  StartNewInvestigation: 'START A NEW INVESTIGATION',
  StartNow: 'Start Now',
  InProgress: 'In Progress',
  FalsePositive: 'False Positive',
  NonMalicious: 'Non Malicious',
  IncidentsResolved: 'Incident(s) resolved',
  RoiSummarySavedTimeLabel: 'Average hours saved per reported email',
  RoiSummaryHourlyLabel: 'Average total cost per hour',
  Engagement: 'Engagement',
  StartAnInvestigation: 'Start an Investigation',
  StopAction: 'Stop Action',
  InvalidURL: 'Invalid URL',
  InvestigateSubLabel: 'Select departments, groups or users to investigate',
  SearchCriteria: 'Search Criteria',
  CompletedUserCount: 'Completed User Count',
  NotStartedUserCount: 'Not Started User Count',
  IntegrationName: 'Integration Name',
  Disable: 'Disable',
  LicenceType: 'License Type',
  ExpiryPeriod: 'Expiry Period',
  NumberOfUsers: 'Number of users',
  ImportSelected: 'IMPORT SELECTED',
  ImportAll: 'IMPORT ALL',
  StartInvestigation: 'START INVESTIGATION',
  CancelImport: 'CANCEL IMPORT',
  KeepEditing: 'KEEP EDITING',
  NotificationTemplate: 'Notification Template',
  MakeAvailableFor: 'Make Available For',
  MakeAvailableForSubtitle: 'Use this setting to make the item avaliable for companies and groups.',
  MakeAvailableForPlaceholder: 'Search companies and groups',
  DeleteNotificationTemplateBody:
    'This notification template will be deleted. All data will be lost.',
  NewNotificationTemplate: 'New Notification Template',
  NewNotificationTemplateSubtitle:
    'Define notification template settings and create email template',
  EditNotificationTemplateSubtitle: 'Define notification template settings and edit email template',
  EditNotificationTemplate: 'Edit Notification Template',
  NewSMTPSetting: 'New SMTP Setting',
  EditSMTPSetting: 'Edit SMTP Setting',
  CancelUserImport: 'Cancel user import?',
  CancelUserImportSubtitle: 'Operation will be abondened',
  CancelUserImportBody: 'You will lose all progress and users will not be imported',
  EmptyCustomApiMessage: 'You do not have any Rest API',
  SubMesCustomApiMessage: 'Create your first Rest API',
  NewCustomApiBtnMessage: 'Create a New Rest API',
  NewCustomApiBtnTooltip: 'Add a New Rest Api',
  CustomApiSubtitle: 'This name will represent the client company',
  CustomApiBodyTitle: 'Add New Integration Client',
  CustomApiEditBodyTitle: 'Edit Integration Client',
  CustomApiBodySubtitle: 'Add new client to provide integration service',
  CustomApiEditBodySubtitle: 'Edit client to provide integration service',
  ClientId: 'Client ID',
  GeneratedClientId: 'Generated Client ID',
  GeneratedClientSecret: 'Generated Client Secret',
  ClientSecret: 'Client Secret',
  DeleteRestApiBody: 'This Rest API will be deleted. All data will be lost.',
  ClientSecretSubtitle: 'Please save API Secret in a safe place. It is only displayed once',
  UserGroupName: 'User group name',
  DefaultHint: '*Required',
  SMTPSettingName: 'SMTP Setting Name',
  SMTPSettingNameSecondLower: 'SMTP setting name',
  SMTPServerAddress: 'SMTP Server Address',
  SMTPServerAddressSecondLower: 'SMTP server address',
  Port: 'Port',
  Message: 'Message',
  EnterIpAdress: 'Enter IP address',
  Retry: 'RETRY',
  NoUrlToDisplay: 'No URL to display',
  EmptyUrl: 'This url is not analyzed',
  AnalysisEngineType: 'Analysis Engine Type',
  Change: 'CHANGE',
  LoginPassword: 'Login Password',
  Security: 'Security',
  Mfa: 'Multi-factor Authentication',
  Enable: 'ENABLE',
  DisableMfa: 'Disable virtual MFA device?',
  EnableMfa: 'Setup Multi-factor Authentication',
  Resync: 'RESYNC',
  Permissions: 'Permissions',
  ADDAPERMISSION: 'Add a permission',
  WhiteLabeling: 'White Labeling',
  WhiteListing: 'Whitelisting',
  FirstSystemUser: 'First System User',
  EmptyMailConfiguration: 'You do not have any mail configurations',
  EmptyMailConfigurationSub: 'Create your first mail configuration',
  EmptyPhishingReporter: 'You do not have any users',
  EmptyCompanyGroups: 'You do not have any company groups',
  EmptySmtpSettings: 'You do not have any smtp settings',
  EmptySmtpSettingsSub: 'Create your first SMTP Setting',
  EmptyNotificationTemplate: 'You do not have any notification templates',
  EmptyNotificationTemplateSub: 'Create your first notification template',
  EmptyProxy: 'You do not have any proxy settings',
  DIFFICULTY: 'Difficulty',
  Preview: 'Preview',
  CreatedBy: 'Created By',
  dnsServiceProviderName: 'Service Provider'
}

export default labels
