export const labels = {
  getMaxLengthMessage(val = '', length = 64) {
    return `${val} cannot exceed ${length} characters`
  },
  getMinLengthMessage(val = '', length = 3) {
    return `${val} must have at least ${length} characters`
  },
  Cancel: 'CANCEL',
  Confirm: 'CONFIRM',
  CannotStartWithSpace: 'Cannot start with space',
  Save: 'SAVE',
  Delete: 'Delete',
  Next: 'NEXT',
  Prev: 'PREV',
  Back: 'BACK',
  Email: 'Email Address',
  FromName: 'From Name',
  Name: 'Name',
  Description: 'Description',
  Low: 'Low',
  High: 'High',
  VeryHigh: 'Very High',
  VeryLow: 'Very Low',
  Category: 'Category',
  EmailSubject: 'Email Subject',
  Industry: 'Industry',
  Result: 'Result',
  Medium: 'Medium',
  Country: 'Country',
  TemplateName: 'Template Name',
  UserName: 'User Name',
  Department: 'Department',
  CreateTime: 'Date Created',
  Address: 'Address',
  WebsiteUrl: 'Website URL',
  FirstName: 'First Name',
  LastName: 'Last Name',
  CompanyName: 'Company Name',
  CompanyGroup: 'Company Group',
  Closed: 'Closed',
  User: 'User',
  Users: 'Users',
  Open: 'Open',
  Matches: 'Match(es)',
  IpAddress: 'Ip Address',
  InvalidDomainName: 'Invalid domain name',
  EmailAddress: 'Email Address',
  StopOngoingInvestigation: 'Stop Ongoing Investigation',
  DoYouWantToStopInvestigation: 'Do you want to stop this investigation?',
  OnceYouStoppedInvestigation: 'Once you stopped, you cannot resume this investigation.',
  Setting: 'Setting',
  Settings: 'Settings',
  Latest: 'Latest',
  Release: 'Release',
  Active: 'Active',
  InActive: 'Inactive',
  AddIn: 'Add-in',
  ReportedEmailTrends: 'Reported Email Trends',
  General: 'General',
  NoUsersToAdd: 'No users to add',
  Brand: 'Brand',
  Reporters: 'Reporters',
  TopRules: 'Top Rules',
  MatchingIncidents: 'Matching Incidents',
  Installation: 'Installation',
  Configuration: 'Configuration',
  MostTriggeredPlaybookRules: 'Most triggered Playbook rules',
  And: 'and',
  Guide: 'Guide',
  Status: 'Status',
  NoRulesConfigured: 'No rules configured',
  CreateNewRule: 'CREATE NEW RULE',
  Playbook: 'Playbook',
  NoMatchEmptyText: 'No Match',
  Actions: 'Actions',
  RuleInformation: 'Rule Information',
  EnterRuleInformation: 'Enter rule information',
  EmptyTopRulesWidget: "There isn't any top rules",
  EmptyTopPostWidget: "There isn't any top posts",
  EmptyRecentlyPostedThreats: "There isn't any recently posted threats, yet",
  EmptyRecentlyReportedIncidents: "There isn't any reported incidents, yet",
  EmptyMatchingIncidents: 'There isn\'t any matching Incidents, yet"',
  EmptyReportedEmailText: "There isn't any reported mail, yet",
  EmptyReportedEmailSubText:
    'Emails that are reported by your users via Phishing Reporter add-in analysed and listed here',
  Community: 'Community',
  AddAnIntegration: 'ADD AN INTEGRATION',
  Logo: 'Logo',
  CompanyLogo: 'Company Logo',
  Close: 'Close',
  RuleName: 'Rule Name',
  MostRecentInvestigations: 'Most recent investigations',
  Heading: 'Heading',
  DialogBox: 'Dialog Box',
  InAnalysis: 'In Analysis',
  Edit: 'Edit',
  PreviewEmail: 'Preview Email',
  TargetUsers: 'Target Users',
  DefineTags: 'Define tags for the rule',
  PhishingReporterSettings: 'PHISHING REPORTER SETTINGS',
  Details: 'Details',
  Priority: 'Priority',
  Tags: 'Tags',
  Investigate: 'Investigate',
  ReportedEmails: 'Reported Emails',
  SummaryOfReportedEmails: 'Summary of emails reported for analysis',
  IncidentClusters: 'Incident Clusters',
  RecentlyPostedThreats: 'Recently Posted Threats',
  RecentlyReportedIncidents: 'Recently Reported Incidents',
  Offline: 'Offline',
  Conditions: 'Conditions',
  RecentInvestigations: 'Recent Investigations',
  InvestigationName: 'Investigation Name',
  RoiSummary: 'ROI Summary',
  Online: 'Online',
  PhishingReporter: 'Phishing Reporter',
  InstallNow: 'Install Now',
  NoAddInInstalled: 'No add-ins installed',
  Required: 'Required',
  NoTargetGroupUserAdded: 'There is no user in this group',
  AlertBox: 'Alertbox',
  CurrentlyOnline: 'Currently Online',
  Subject: 'Subject',
  Saved: 'Saved',
  NoEmailAnalysed: 'No emails analysed',
  Money: 'Money',
  Auto: 'Auto',
  Investigations: 'Investigations',
  Manual: 'Manual',
  FoundHarmful: 'Found harmful',
  IncidentAnalysis: 'Incident Analysis',
  Progress: 'Progress',
  InvalidEmailAddress: 'Invalid email address',
  SaveAndDownload: 'Save and Download',
  SaveChanges: 'Save Changes',
  NoInvestigationStarted: 'No investigation started',
  NoInvestigation: 'No investigations',
  StartNewInvestigation: 'START A NEW INVESTIGATION',
  StartNow: 'Start Now',
  InProgress: 'In Progress',
  FalsePositive: 'False Positive',
  NonMalicious: 'Non Malicious',
  IncidentsResolved: 'Incident(s) resolved',
  RoiSummarySavedTimeLabel: 'Average hours saved per reported email',
  RoiSummaryHourlyLabel: 'Average total cost per hour',
  Engagement: 'Engagement',
  StartAnInvestigation: 'Start an Investigation',
  StopAction: 'Stop Action',
  InvalidURL: 'Invalid URL',
  InvestigateSubLabel: 'Select departments, groups or users to investigate',
  SearchCriteria: 'Search Criteria',
  CompletedUserCount: 'Completed User Count',
  NotStartedUserCount: 'Not Started User Count',
  IntegrationName: 'Integration Name',
  Disable: 'Disable',
  LicenceType: 'Licence Type',
  ExpiryPeriod: 'Expiry Period',
  NumberOfUsers: 'Number of users',
  ImportSelected: 'IMPORT SELECTED',
  ImportAll: 'IMPORT ALL',
  StartInvestigation: 'START INVESTIGATION',
  CancelImport: 'CANCEL IMPORT',
  KeepEditing: 'KEEP EDITING'
}

export default labels
