import TrainingLibraryNewScreensaverInformation from '@/components/TrainingLibrary/TrainingLibraryNewModal/TrainingLibraryNewScreensaverModal/TrainingLibraryNewScreensaverInformation.vue'

describe('TrainingLibraryNewScreensaverInformation.vue', () => {
  it('canAutoGenerateDescription requires name, category, roleIds', () => {
    expect(
      TrainingLibraryNewScreensaverInformation.computed.canAutoGenerateDescription.call({
        formData: { name: '', category: '', roleIds: [], description: '' },
        isGenerateLoading: false,
        hasGenerated: false,
        hasGenerationError: false
      })
    ).toBeFalsy()
    expect(
      TrainingLibraryNewScreensaverInformation.computed.canAutoGenerateDescription.call({
        formData: { name: 'x', category: 'c', roleIds: [1], description: '' },
        isGenerateLoading: false,
        hasGenerated: false,
        hasGenerationError: false
      })
    ).toBe(true)
  })

  it('isGenerateDisabled returns false when description has content', () => {
    expect(
      TrainingLibraryNewScreensaverInformation.computed.isGenerateDisabled.call({
        formData: { name: 'x', category: 'c', roleIds: [1], description: 'Long enough desc' },
        isGenerateLoading: false
      })
    ).toBe(false)
  })

  it('setFormData merges formData and sets coverImageUrl', () => {
    const ctx = { formData: { name: '', coverImageUrl: null } }
    TrainingLibraryNewScreensaverInformation.methods.setFormData.call(ctx, {
      name: 'New Screensaver',
      coverImage: { imageUrl: 'https://example.com/img.png' }
    })
    expect(ctx.formData.name).toBe('New Screensaver')
    expect(ctx.formData.coverImageUrl).toBe('https://example.com/img.png')
  })

  it('setMakeAvailableForData sets MyCompanyOnly when empty', () => {
    const ctx = {
      formData: { availableForRequests: [] },
      $refs: {}
    }
    TrainingLibraryNewScreensaverInformation.methods.setMakeAvailableForData.call(ctx, [])
    expect(ctx.formData.availableForRequests[0].type).toBe('MyCompanyOnly')
  })
})
