# trigger: 
#   branches:
#     include:
#     - dev
  #   exclude:
  #   - staging
  #   - master
  #   - release/*

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: self # In a different organization
    type: git
    name: Keepnet/KeepnetLabs.UI
    ref: dev
    trigger:
    - dev
  - repository: GitHub_Prod_Repo # In a different organization
    type: git
    name: Keepnet/KeepnetLabs.UI
    ref: $(Build.SourceBranch)
    trigger:
    - release/*
  - repository: GitHub_Staging_Repo # In a different organization
    type: git
    name: Keepnet/KeepnetLabs.UI
    ref: staging
    trigger:
    - staging
# parameters:
# - name: runAll
#   displayName: 'Run all Services and Deploy to'
#   type: string
#   default: None 
#   values:
#     - None
#     - DEV
#     - STAGING
#     - PREPROD
#     - PROD  

# - name: runService
#   displayName: 'Run specific service'
#   type: string
#   default: None 
#   values:
#     - None
#     - UI

stages:
# BUILD DEV
- stage: CI_Dev 
  jobs:
  - job: Build_UI
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/devops'))
    steps:
      - template: sub-KeepnetLabs.UI-CI.yml

# # BUILD STAGING
- stage: CI_Staging
  jobs:   
  - job: Build_UI
    condition: and(in(dependencies.CI_Dev.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))
    steps:
      - template: sub-KeepnetLabs.UI-CI.yml

# # BUILD PREPROD
# - stage: CI_PreProd
#   jobs:   
#   - job: Build_UI
#     condition: and(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')),or(eq('${{parameters.runService}}', 'None'), eq('${{parameters.runService}}', 'UI')))
#     steps:
#       - template: sub-KeepnetLabs.UI-CI.yml

# # BUILD PROD
- stage: CI_Prod
  jobs:   
  - job: Build_UI
    condition: and(in(dependencies.CI_Staging.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'), contains(variables['Build.SourceBranch'], 'refs/heads/release'))
    steps:
      - template: sub-KeepnetLabs.UI-CI.yml

# DEPLOY DEV NEW
- stage: DEV
  variables:
  - group: Dev-UI-Config
  condition: and(in(dependencies.CI_Dev.result, 'Succeeded', 'SucceededWithIssues'), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))  
  dependsOn: CI_Dev
  jobs:
    - template: sub-KeepnetLabs.UI-CD.yml
      parameters:
          jobName: 'Deploy_UI'
          environment: 'DEV_UI'
          websiteName: 'DevUI'
          artifactName: 'drop'


# # DEPLOY STAGING          
- stage: STG
  variables:
  - group: Staging-UI-Config
  condition: and(in(dependencies.CI_Staging.result, 'Succeeded', 'SucceededWithIssues'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))  
  dependsOn: CI_Staging
  jobs:
    - template: sub-KeepnetLabs.UI-CD.yml
      parameters:
          jobName: 'Deploy_UI'
          environment: 'STAGING_UI'
          websiteName: 'TestUI'
          artifactName: 'drop'

# # DEPLOY PREPROD          
# - stage: PREPROD
#   variables:
#   - group: Prod-UI-Config
#   condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))  
#   dependsOn: CI_PreProd
#   jobs:
#     - template: sub-KeepnetLabs.UI-CD.yml
#       parameters:
#           jobName: 'Deploy_UI'
#           environment: 'PREPROD'
#           websiteName: 'PreProdUI'
#           artifactName: 'drop'

# # DEPLOY PROD          
- stage: PROD
  variables:
  - group: Prod-UI-Config
  condition: and(in(dependencies.CI_Prod.result, 'Succeeded', 'SucceededWithIssues'), contains(variables['Build.SourceBranch'], 'refs/heads/release'))  
  dependsOn: CI_Prod
  jobs:
    - template: sub-KeepnetLabs.UI-CD.yml
      parameters:
          jobName: 'Deploy_UI'
          environment: 'PROD_UI'
          websiteName: 'UI'
          artifactName: 'drop'

- stage: GH_Repo_STG
  variables:
  - group: Staging-UI-Config
  dependsOn: STG
  condition: and(in(dependencies.STG.result, 'Succeeded', 'SucceededWithIssues'), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))  
  jobs:
  - template: sub-KeepnetLabs.UI-GH.yml
    parameters:
      repositoryName: GitHub_Staging_Repo
      environment: STAGING_UI
      githubConnectionUrl: $(testGitHubConnectionURL)

- stage: GH_Repo_PROD
  variables:
  - group: Prod-UI-Config
  dependsOn: CI_Prod
  condition: and(in(dependencies.CI_Prod.result, 'Succeeded', 'SucceededWithIssues'), contains(variables['Build.SourceBranch'], 'refs/heads/release')) 
  jobs:
  - template: sub-KeepnetLabs.UI-GH.yml
    parameters:
      repositoryName: GitHub_Prod_Repo
      environment: PROD_UI
      githubConnectionUrl: $(prodGitHubConnectionURL)

- stage: ONPREM_BUCKET
  variables:
  - group: OnPrem-UI-Config
  dependsOn: CI_Prod
  condition: and(in(dependencies.CI_Prod.result, 'Succeeded', 'SucceededWithIssues'), contains(variables['Build.SourceBranch'], 'refs/heads/release')) 
  jobs:
  - deployment: Upload_to_Bucket
    workspace:
      clean: all 
    displayName: Upload_to_S3_Bucket
    environment: PROD_UI
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in config.js'
            inputs:
              rootDirectory: '$(Pipeline.Workspace)/drop'
              targetFiles: config.js

          - task: ArchiveFiles@2
            displayName: 'Archive API'
            inputs:
              rootFolderOrFile: '$(Pipeline.Workspace)/drop/'
              archiveFile: '$(Pipeline.Workspace)/ui/$(Build.BuildNumber).zip'

          - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
            displayName: 'S3 Upload: API-Master'
            inputs:
              awsCredentials: 'AWS-S3-Connection'
              regionName: 'us-east-1'
              bucketName: 'keepnetlabs-dev'
              sourceFolder: '$(Pipeline.Workspace)/ui'
              globExpressions: '**/$(Build.BuildNumber).zip'
              targetFolder: 'next-ui-artifacts/drop/ui'
              filesAcl: 'authenticated-read'
              createBucket: true
