trigger: none

pr:
  branches:
    include:
      - dev
      - test

pool:
  vmImage: ubuntu-latest

variables:
- group: Qodana-Props-UI

steps:
  - checkout: self
    fetchDepth: 0
    persistCredentials: true
  - task: Cache@2
    inputs:
      key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
      path: '$(Agent.TempDirectory)/qodana/cache'
      restoreKeys: |
        "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
        "$(Build.Repository.Name)"
  - task: QodanaScan@2026
    inputs:
      prMode: true
      postPrComment: true
      uploadResult: true
      args: '--fail-threshold,0'
    env:
      QODANA_TOKEN: $(QODANA_TOKEN)
      QODANA_ENDPOINT: $(QODANA_ENDPOINT)

