
parameters:
- name: repositoryName
  displayName: Repository Name
  type: string

- name: environment
  displayName: Environment
  type: string

- name: githubConnectionUrl
  displayName: GitHub Connection URL
  type: string

jobs:
- deployment: Push_GH
  workspace:
    clean: all 
  displayName: Push_GH
  environment:
    name: '${{ parameters.environment }}'
    resourceType: VirtualMachine 
  strategy:
    runOnce:
      deploy:
        steps:
        - download: none
        - checkout: ${{ parameters.repositoryName }}
          path: ${{ parameters.repositoryName }}
          fetchDepth: 0

        - script: dir $(Build.SourcesDirectory)

        - script: |
            git push ${{ parameters.githubConnectionUrl }} --delete test
            git checkout -b test
          # workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.repositoryName }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Github Test Deployment Checkout'

        - script: |
            rm public/3da9996d-1c60-461b-a56c-430f3ea053f4.js
            mv public/config.Production.js public/3da9996d-1c60-461b-a56c-430f3ea053f4.js
          # workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.repositoryName }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Config.js Changes'

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in 3da9996d-1c60-461b-a56c-430f3ea053f4.js'
          inputs:
            # rootDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.repositoryName }}/public'
            rootDirectory: '$(System.DefaultWorkingDirectory)/public'
            targetFiles: '3da9996d-1c60-461b-a56c-430f3ea053f4.js'

        - script: |
            git config --global user.email "keepnetlabs@keepnetlabs.com"
            git config --global user.name "Keepnetlabs"
          # workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.repositoryName }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Github User Cred'

        - script: |
            git add .
            git commit -m "config.js updated"
          # workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.repositoryName }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)'  
          displayName: 'Github Add and Commit Config.js'

        - script: 'git push ${{ parameters.githubConnectionUrl }} '
          # workingDirectory: '$(System.DefaultWorkingDirectory)/${{ parameters.repositoryName }}'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          displayName: 'Github Test Deployment Push'

