sonar.projectKey=Keepnet
sonar.projectName=KeepnetLabs.UI
sonar.host.url=http://localhost:9000

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/public/**,**/*.spec.js,**/*.spec.ts,**/tests/**

sonar.tests=tests
sonar.test.inclusions=**/*.spec.js,**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info