import axios from 'axios'

const AI_DESCRIPTION_WORKER_URL =
  'https://ai-description.keepnet-labs-ltd-business-profile4086.workers.dev/description'

export default {
  computed: {
    /**
     * Checks if all required fields are filled for AI generation
     * Component'lerde override edilebilir
     * @returns {boolean}
     */
    canAutoGenerateDescription() {
      return (
        this.formData?.name &&
        this.formData?.category &&
        this.formData?.targetAudience &&
        !this.formData?.description &&
        !this.isGenerateLoading &&
        !this.hasGenerated
      )
    }
  },
  watch: {
    /**
     * Auto-generate description when all required fields are filled and description is empty
     */
    canAutoGenerateDescription: {
      handler(canGenerate) {
        if (canGenerate) {
          this.handleGenerate()
        }
      },
      immediate: false
    }
  },
  methods: {
    /**
     * Prepares AI description generation payload from form data
     * @returns {Object} Payload object with name, category, compliance, behaviour, and role
     */
    getAIDescriptionPayload() {
      return {
        name: this.formData?.name || '',
        category: this.formData?.category || '',
        compliance: this.formData?.compliances || [],
        behaviour: this.formData?.behaviours || [],
        role: this.formData?.targetAudience || ''
      }
    },

    /**
     * Generates AI description by calling the Cloudflare Worker API.
     *
     * The same worker is shared across content domains. The `type` field tells
     * the worker which prompt to use (e.g. 'training', 'phishing', 'quishing',
     * 'smishing'). Any extra domain-specific fields can be passed via `fields`
     * and are forwarded as-is in the payload.
     *
     * @param {Object} options - Options for generation
     * @param {string} [options.name] - Content name
     * @param {string} [options.category] - Category of the content
     * @param {string} [options.role] - Target audience role
     * @param {string} [options.description] - Existing description (for improvement)
     * @param {string} [options.type] - Content type discriminator for prompt selection
     * @param {Object} [options.fields] - Extra domain-specific fields to include in the payload
     * @returns {Promise<string>} Generated or improved description
     */
    async generateAIDescription({
      name = '',
      category = '',
      role = '',
      description = '',
      type = 'training',
      fields = {}
    } = {}) {
      const payload = {
        type,
        name: name.trim(),
        category: category.trim(),
        role: role.trim(),
        ...fields
      }

      // Include existing description if we're improving it
      if (description && description.trim().length > 5) {
        payload.description = description.trim()
      }

      const response = await axios.post(AI_DESCRIPTION_WORKER_URL, payload, {
        headers: {
          'Content-Type': 'application/json'
        }
      })

      return response.data?.description || ''
    },

    /**
     * Generates description if empty and required fields are filled
     * Returns a promise that resolves when generation is complete or immediately if not needed
     * @returns {Promise<boolean>} True if generation happened, false otherwise
     */
    async generateDescriptionIfNeeded() {
      const hasRequiredFields =
        this.formData?.name && this.formData?.category && this.formData?.targetAudience

      const descriptionEmpty =
        !this.formData?.description || this.formData.description.trim().length === 0

      if (hasRequiredFields && descriptionEmpty && !this.isGenerateLoading) {
        await this.handleGenerate()
        return true
      }
      return false
    }
  }
}
