<template>
  <div class="phishing-activity-table-wrapper">
    <DataTable
      ref="refPhishingActivityTable"
      class="phishing-activity-table"
      :columns="columns"
      :table="tableData"
      :empty="empty"
      :show-pagination="true"
      :show-page-size="true"
      :show-filter-options="false"
      :show-datatable-row-actions="false"
      :filterable="true"
      :options="true"
      :count-row="5"
    />
  </div>
</template>

<script>
import DataTable from "@/components/DataTable";
import { getExecutiveReportChartData } from "@/api/reports";

export default {
  name: "ExecutiveReportPhishingActivityTable",
  components: {
    DataTable,
  },
  props: {
    editMode: {
      type: Boolean,
      default: true,
    },
    card: {
      type: Object,
      default: () => ({}),
    },
    dateRange: {
      type: Array,
      default: () => [],
    },
    datePeriod: {
      type: Number,
      default: 1,
    },
    defaultWidgetData: {
      type: [Object, Array],
    },
    dateFormat: {
      type: String,
      default: "",
    },
  },
  data() {
    return {
      isLoading: false,
      tableTitle: "Phishing Activity Details",
      tableData: [],
      columns: [
        {
          property: "firstName",
          label: "First Name",
          align: "left",
          show: true,
          type: "text",
          sortable: true,
          width: 120,
        },
        {
          property: "lastName",
          label: "Last Name",
          align: "left",
          show: true,
          type: "text",
          sortable: true,
          width: 120,
        },
        {
          property: "email",
          label: "Email",
          align: "left",
          show: true,
          type: "text",
          sortable: true,
          width: 200,
        },
        {
          property: "campaignName",
          label: "Campaign Name",
          align: "left",
          show: true,
          type: "text",
          sortable: true,
          width: 180,
        },
        {
          property: "scenarioName",
          label: "Scenario Name",
          align: "left",
          show: true,
          type: "text",
          sortable: true,
          width: 180,
        },
        {
          property: "category",
          label: "Category",
          align: "left",
          show: true,
          type: "text",
          sortable: true,
          width: 120,
        },
        {
          property: "difficulty",
          label: "Difficulty",
          align: "center",
          show: true,
          type: "text",
          sortable: true,
          width: 180,
        },
        {
          property: "opened",
          label: "Opened",
          align: "center",
          show: true,
          type: "number",
          sortable: true,
          width: 180,
        },
        {
          property: "clicked",
          label: "Clicked",
          align: "center",
          show: true,
          type: "number",
          sortable: true,
          width: 180,
        },
      ],
      empty: {
        message: "No phishing activity data available",
      },
    };
  },
  watch: {
    dateRange() {
      this.callForData();
    },
  },
  created() {
    // TODO: Remove mock data after testing
    this.setMockTableData();
    return;
    // Original code below
    if (this?.defaultWidgetData?.length) {
      this.setTableData(this.defaultWidgetData);
    } else {
      this.callForData();
    }
  },
  methods: {
    setMockTableData() {
      // Mock data for testing
      this.tableData = [
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
        {
          firstName: "John",
          lastName: "Doe",
          email: "john.doe@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Fake Invoice Attack",
          category: "Financial",
          difficulty: "High",
          opened: 3,
          clicked: 1,
        },
        {
          firstName: "Jane",
          lastName: "Smith",
          email: "jane.smith@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Gift Card Scam",
          category: "Social Engineering",
          difficulty: "Medium",
          opened: 5,
          clicked: 2,
        },
        {
          firstName: "Robert",
          lastName: "Johnson",
          email: "robert.j@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "Password Reset",
          category: "Credential Theft",
          difficulty: "Low",
          opened: 2,
          clicked: 0,
        },
        {
          firstName: "Emily",
          lastName: "Williams",
          email: "emily.w@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Tech Support Scam",
          category: "Technical",
          difficulty: "High",
          opened: 4,
          clicked: 3,
        },
        {
          firstName: "Michael",
          lastName: "Brown",
          email: "michael.b@company.com",
          campaignName: "Holiday Phishing Test",
          scenarioName: "Delivery Notification",
          category: "Shipping",
          difficulty: "Medium",
          opened: 1,
          clicked: 0,
        },
        {
          firstName: "Sarah",
          lastName: "Davis",
          email: "sarah.d@company.com",
          campaignName: "CEO Fraud Test",
          scenarioName: "Urgent Wire Transfer",
          category: "Financial",
          difficulty: "High",
          opened: 6,
          clicked: 4,
        },
        {
          firstName: "David",
          lastName: "Miller",
          email: "david.m@company.com",
          campaignName: "Q4 Security Awareness",
          scenarioName: "LinkedIn Request",
          category: "Social Media",
          difficulty: "Low",
          opened: 2,
          clicked: 1,
        },
        {
          firstName: "Lisa",
          lastName: "Garcia",
          email: "lisa.g@company.com",
          campaignName: "IT Support Simulation",
          scenarioName: "Software Update",
          category: "Technical",
          difficulty: "Medium",
          opened: 3,
          clicked: 2,
        },
      ];
      this.isLoading = false;
    },
    callForData() {
      this.isLoading = true;
      const payload = {
        widgetIds: [this.card.resourceId],
        datePeriod: this.datePeriod,
        startDate: this.dateRange[0],
        endDate: this.dateRange[1],
      };
      getExecutiveReportChartData(payload)
        .then((response) => {
          const {
            data: { data },
          } = response || {};
          this.$emit("on-set-default-widget-data", this.card.key, data);
          this.setTableData(data);
        })
        .finally(() => {
          this.isLoading = false;
        });
    },
    setTableData(data) {
      if (!data || !data.length) {
        this.tableData = [];
        return;
      }

      const widgetData = data[0]?.widgetDatas;
      if (!widgetData || !widgetData.length) {
        this.tableData = [];
        return;
      }

      // Map the data to table format
      this.tableData = widgetData.map((item) => ({
        firstName: item.firstName || "",
        lastName: item.lastName || "",
        email: item.email || "",
        campaignName: item.campaignName || "",
        scenarioName: item.scenarioName || "",
        category: item.category || "",
        difficulty: item.difficulty || "",
        opened: item.opened || 0,
        clicked: item.clicked || 0,
      }));
    },
    handleDelete() {
      this.$emit("on-delete", this.card);
    },
    handleEdit() {
      this.$emit("on-edit", this.card);
    },
  },
};
</script>
