import { PROPERTY_STORE } from '@/model/constants/commonConstants'
import labels from '@/model/constants/labels'

export const COLUMNS = {
  FIRST_NAME: {
    property: PROPERTY_STORE.FIRSTNAME,
    align: 'left',
    label: labels.FirstName,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_NAME: {
    property: PROPERTY_STORE.LASTNAME,
    align: 'left',
    label: labels.LastName,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  EMAIL: {
    property: PROPERTY_STORE.EMAIL,
    align: 'left',
    label: labels.Email,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  EMAIL_SEND_DATE: {
    property: 'lastSendingTime',
    align: 'left',
    editable: false,
    label: labels.EmailSendDate,
    sortable: true,
    show: true,
    type: 'text',
    width: 200,
    filterableType: 'date'
  },
  DATA: {
    property: 'submittedData',
    align: 'left',
    label: labels.Data,
    fixed: 'right',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  DEPARTMENT: {
    property: PROPERTY_STORE.DEPARTMENT,
    align: 'left',
    label: labels.Department,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  SCENARIO: {
    property: 'phishingScenarioName',
    align: 'left',
    label: labels.Scenario,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text',
    filterableCustomFieldName: 'Scenario'
  },
  LAST_OPENED: {
    property: 'lastOpenedTime',
    align: 'left',
    fixed: false,
    editable: false,
    label: labels.LastOpened,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'date'
  },
  TIMES_OPENED: {
    property: 'openedCount',
    align: 'right',
    editable: false,
    label: labels.TimesOpened,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'numeric',
    filterableCustomFieldName: 'TimesOpened'
  },
  DATE_CLICKED: {
    property: 'clickedTime',
    align: 'left',
    label: labels.DateClicked,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  SUBMITTED_TIME: {
    property: 'submittedTime',
    align: 'left',
    label: labels.DateClicked,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  DATE_OPENED: {
    property: 'openedTime',
    align: 'left',
    label: labels.DateOpened,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  USER_AGENT: {
    property: PROPERTY_STORE.USERAGENT,
    align: 'left',
    label: labels.UserAgent,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  BROWSER: {
    property: 'browserName',
    align: 'left',
    label: labels.Browser,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  GEOLOCATION: {
    property: 'userGeolocation',
    align: 'left',
    label: labels.Geolocation,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  IP: {
    property: 'userIpAddressList',
    align: 'left',
    label: labels.Ip,
    fixed: 'right',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  SUBMITTED_DATA_IP: {
    property: 'userIpAddressList',
    align: 'left',
    label: labels.Ip,
    fixed: 'false',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_CLICKED: {
    property: 'lastClickedTime',
    align: 'left',
    label: labels.LastClicked,
    fixed: false,
    sortable: true,
    show: true,
    type: 'date',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  TIMES_CLICKED: {
    property: 'clickedCount',
    align: 'right',
    editable: false,
    label: labels.TimesClicked,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'numeric',
    filterableCustomFieldName: 'TimesClicked'
  },
  PASSWORD_COMPLEXITY: {
    property: 'minPasswordComplexity',
    align: 'center',
    label: labels.PasswordComplexity,
    fixed: false,
    sortable: true,
    show: true,
    type: 'badge',
    width: 200,
    filterableType: 'select',
    filterableCustomFieldName: 'PasswordComplexity'
  },
  LAST_SUBMISSION: {
    property: 'lastSubmittedTime',
    align: 'left',
    label: labels.LastSubmission,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  TIMES_SUBMISSION: {
    property: 'submittedCount',
    align: 'right',
    label: labels.TimesSubmission,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'numeric',
    filterableCustomFieldName: 'TimesSubmission'
  },
  LAST_SENDING_DATE: {
    property: PROPERTY_STORE.LAST_SENDING_DATE,
    align: 'left',
    label: labels.LastSendingDate,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  SENDING_REPORT_LAST_SENDING_DATE: {
    property: 'lastSubmittedTime',
    align: 'left',
    label: labels.LastSendingDate,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  LAST_SENDING_STATUS: {
    property: 'status',
    align: 'center',
    label: labels.LAST_SENDING_STATUS,
    sortable: true,
    show: true,
    type: 'badge',
    width: 200,
    filterableType: 'select',
    props: {
      style: {
        maxWidth: '120px'
      }
    },
    filterableCustomFieldName: 'LastSendingStatus'
  },
  SMTP: {
    property: PROPERTY_STORE.SMTP,
    align: 'left',
    label: labels.Smtp,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'text'
  }
}
