import { PROPERTY_STORE } from '@/model/constants/commonConstants'
import labels from '@/model/constants/labels'

export const COLUMNS = {
  FIRST_NAME: {
    property: PROPERTY_STORE.FIRSTNAME,
    align: 'left',
    label: labels.FirstName,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_NAME: {
    property: PROPERTY_STORE.LASTNAME,
    align: 'left',
    label: labels.LastName,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  EMAIL: {
    property: PROPERTY_STORE.EMAIL,
    align: 'left',
    label: labels.Email,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  EMAIL_SEND_DATE: {
    property: PROPERTY_STORE.EMAIL_SEND_DATE,
    align: 'left',
    editable: false,
    label: labels.EmailSendDate,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'date'
  },
  DATA: {
    property: PROPERTY_STORE.DATA,
    align: 'left',
    label: labels.Data,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  DEPARTMENT: {
    property: PROPERTY_STORE.DEPARTMENT,
    align: 'left',
    label: labels.Department,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  SCENARIO: {
    property: 'phishingScenarioName',
    align: 'left',
    label: labels.Scenario,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_OPENED: {
    property: 'lastOpenedTime',
    align: 'left',
    editable: false,
    label: labels.LastOpened,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'date'
  },
  TIMES_OPENED: {
    property: 'openedCount',
    align: 'left',
    editable: false,
    label: labels.TimesOpened,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'numeric'
  },
  DATE_CLICKED: {
    property: PROPERTY_STORE.DATECLICKED,
    align: 'left',
    label: labels.DateClicked,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  DATE_OPENED: {
    property: 'openedTime',
    align: 'left',
    label: labels.DateOpened,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  USER_AGENT: {
    property: PROPERTY_STORE.USERAGENT,
    align: 'left',
    label: labels.UserAgent,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  BROWSER: {
    property: 'browserName',
    align: 'left',
    label: labels.Browser,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  GEOLOCATION: {
    property: 'userGeolocation',
    align: 'left',
    label: labels.Geolocation,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  IP: {
    property: 'userIpAddressList',
    align: 'left',
    label: labels.Ip,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_CLICKED: {
    property: PROPERTY_STORE.LASTCLICKED,
    align: 'left',
    label: labels.LastClicked,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'date',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  TIMES_CLICKED: {
    property: PROPERTY_STORE.TIMESCLICKED,
    align: 'left',
    editable: false,
    label: labels.TimesClicked,
    sortable: true,
    show: true,
    type: 'numeric',
    width: 160,
    filterableType: 'numeric'
  },
  PASSWORD_COMPLEXITY: {
    property: PROPERTY_STORE.PASSWORD_COMPLEXITY,
    align: 'center',
    label: labels.PasswordComplexity,
    sortable: true,
    show: true,
    type: 'badge',
    width: 160,
    filterableType: 'select'
  },
  LAST_SUBMISSION: {
    property: PROPERTY_STORE.LAST_SUBMISSION,
    align: 'left',
    label: labels.LastSubmission,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  TIMES_SUBMISSION: {
    property: PROPERTY_STORE.TIMES_SUBMISSION,
    align: 'left',
    label: labels.TimesSubmission,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'numeric'
  },
  LAST_SENDING_DATE: {
    property: PROPERTY_STORE.LAST_SENDING_DATE,
    align: 'left',
    label: labels.LastSendingDate,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  LAST_SENDING_STATUS: {
    property: PROPERTY_STORE.LAST_SENDING_STATUS,
    align: 'center',
    label: labels.LAST_SENDING_STATUS,
    sortable: true,
    show: true,
    type: 'slot',
    width: 160,
    filterableType: 'select'
  },
  SMTP: {
    property: PROPERTY_STORE.SMTP,
    align: 'left',
    label: labels.Smtp,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'text'
  }
}
