import TrainingLibraryNewInfographicInformation from '@/components/TrainingLibrary/TrainingLibraryNewModal/TrainingLibraryNewInfographicModal/TrainingLibraryNewInfographicInformation.vue'

describe('TrainingLibraryNewInfographicInformation.vue', () => {
  it('canAutoGenerateDescription requires name, category, and roleIds', () => {
    expect(
      TrainingLibraryNewInfographicInformation.computed.canAutoGenerateDescription.call({
        formData: { name: '', category: '', roleIds: [], description: '' },
        isGenerateLoading: false,
        hasGenerated: false,
        hasGenerationError: false
      })
    ).toBeFalsy()

    expect(
      TrainingLibraryNewInfographicInformation.computed.canAutoGenerateDescription.call({
        formData: { name: 'n', category: 'c', roleIds: [1], description: '' },
        isGenerateLoading: false,
        hasGenerated: false,
        hasGenerationError: false
      })
    ).toBe(true)
  })

  it('setFormData merges and sets coverImageUrl', () => {
    const ctx = { formData: { name: '', coverImageUrl: null } }
    TrainingLibraryNewInfographicInformation.methods.setFormData.call(ctx, {
      name: 'New Infographic',
      coverImage: { imageUrl: 'https://example.com/cover.png' }
    })
    expect(ctx.formData.name).toBe('New Infographic')
    expect(ctx.formData.coverImageUrl).toBe('https://example.com/cover.png')
  })

  it('setMakeAvailableForData sets MyCompanyOnly as fallback', () => {
    const ctx = { formData: { availableForRequests: [] }, $refs: {} }
    TrainingLibraryNewInfographicInformation.methods.setMakeAvailableForData.call(ctx, [])
    expect(ctx.formData.availableForRequests[0].type).toBe('MyCompanyOnly')
  })
})
