import TrainingLibraryNewLearningPathInformation from '@/components/TrainingLibrary/TrainingLibraryNewModal/TrainingLibraryNewLearningPathModal/TrainingLibraryNewLearningPathInformation.vue'

describe('TrainingLibraryNewLearningPathInformation.vue', () => {
  it('canAutoGenerateDescription requires name, category, and roleIds', () => {
    expect(
      TrainingLibraryNewLearningPathInformation.computed.canAutoGenerateDescription.call({
        formData: { name: '', category: '', roleIds: [], description: '' },
        isGenerateLoading: false,
        hasGenerated: false,
        hasGenerationError: false
      })
    ).toBeFalsy()

    expect(
      TrainingLibraryNewLearningPathInformation.computed.canAutoGenerateDescription.call({
        formData: { name: 'n', category: 'c', roleIds: [1], description: '' },
        isGenerateLoading: false,
        hasGenerated: false,
        hasGenerationError: false
      })
    ).toBe(true)
  })

  it('isGenerateDisabled returns false when description is long enough', () => {
    const value = TrainingLibraryNewLearningPathInformation.computed.isGenerateDisabled.call({
      formData: { name: 'n', category: 'c', roleIds: [1], description: 'Long enough description' },
      isGenerateLoading: false
    })
    expect(value).toBe(false)
  })

  it('setMakeAvailableForData sets fallback MyCompanyOnly', () => {
    const ctx = { formData: { availableForRequests: [] }, $refs: {} }
    TrainingLibraryNewLearningPathInformation.methods.setMakeAvailableForData.call(ctx, [])
    expect(ctx.formData.availableForRequests[0].type).toBe('MyCompanyOnly')
  })
})
