import { PROPERTY_STORE } from '@/model/constants/commonConstants'
import labels from '@/model/constants/labels'

export const COLUMNS = {
  FIRST_NAME: {
    property: PROPERTY_STORE.FIRSTNAME,
    align: 'left',
    label: labels.FirstName,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  PHISHING_SCENARIO_NAME: {
    property: PROPERTY_STORE.PHISHING_SCENARIO_NAME,
    align: 'left',
    label: labels.ScenarioName,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_NAME: {
    property: PROPERTY_STORE.LASTNAME,
    align: 'left',
    label: labels.LastName,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  EMAIL: {
    property: PROPERTY_STORE.EMAIL,
    align: 'left',
    label: labels.Email,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  EMAIL_SEND_DATE: {
    property: 'lastSendingTime',
    align: 'left',
    editable: false,
    label: labels.EmailSendDate,
    sortable: true,
    show: true,
    type: 'text',
    width: 200,
    filterableType: 'date'
  },
  DATA: {
    property: 'submittedData',
    align: 'left',
    label: labels.Data,
    fixed: 'right',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  DEPARTMENT: {
    property: PROPERTY_STORE.DEPARTMENT,
    align: 'left',
    label: labels.Department,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  PREFERREDLANGUAGE: {
    property: 'preferredLanguage',
    align: 'left',
    label: labels.PreferredLanguage,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 200,
    isEditable: false,
    filterableType: 'select',
    filterableItems: [],
    filterableCustomFieldName: 'preferredLanguageId'
  },
  SCENARIO: {
    property: 'phishingScenarioName',
    align: 'left',
    label: labels.Scenario,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_OPENED: {
    property: 'lastAttachmentOpenedTime',
    align: 'left',
    fixed: false,
    editable: false,
    label: labels.LastOpened,
    sortable: true,
    show: true,
    type: 'slot',
    width: 160,
    filterableType: 'date'
  },
  LAST_REPORTED: {
    property: 'lastReportedTime',
    align: 'left',
    fixed: false,
    editable: false,
    label: labels.LastReported,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'date'
  },
  DATE_REPORTED: {
    property: 'reportedTime',
    align: 'left',
    fixed: false,
    editable: false,
    label: labels.DateReported,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'date'
  },
  TIMES_OPENED: {
    property: 'attachmentOpenedCount',
    align: 'right',
    editable: false,
    label: labels.TimesOpened,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'number'
  },
  TIMES_REPORTED: {
    property: 'reportedCount',
    align: 'right',
    editable: false,
    label: labels.TimesReported,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'number'
  },
  DATE_CLICKED: {
    property: 'clickedTime',
    align: 'left',
    label: labels.DateClicked,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  SUBMITTED_TIME: {
    property: 'submittedTime',
    align: 'left',
    label: labels.DateClicked,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  DATE_OPENED: {
    property: 'openedTime',
    align: 'left',
    label: labels.DateOpened,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'slot',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  USER_AGENT: {
    property: PROPERTY_STORE.USERAGENT,
    align: 'left',
    label: labels.UserAgent,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  BROWSER: {
    property: 'browserName',
    align: 'left',
    label: labels.Browser,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  GEOLOCATION: {
    property: 'userGeolocation',
    align: 'left',
    label: labels.Geolocation,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  IP: {
    property: 'userIpAddressList',
    align: 'left',
    label: labels.Ip,
    fixed: 'right',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  IP_PHISHING_REPORTER: {
    property: 'userIpAddressList',
    align: 'left',
    label: labels.Ip,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  SUBMITTED_DATA_IP: {
    property: 'userIpAddressList',
    align: 'left',
    label: labels.Ip,
    fixed: 'false',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'text'
  },
  LAST_CLICKED: {
    property: 'lastClickedTime',
    align: 'left',
    label: labels.LastClicked,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  TIMES_CLICKED: {
    property: 'clickedCount',
    align: 'right',
    editable: false,
    label: labels.TimesClicked,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'number'
  },
  PASSWORD_COMPLEXITY: {
    property: 'minPasswordComplexity',
    align: 'center',
    label: labels.PasswordComplexity,
    fixed: false,
    sortable: true,
    show: true,
    type: 'badge',
    width: 225,
    filterableType: 'select'
  },
  LAST_SUBMISSION: {
    property: 'lastSubmittedTime',
    align: 'left',
    label: labels.LastSubmission,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  TIMES_SUBMISSION: {
    property: 'submittedCount',
    align: 'right',
    label: labels.TimesSubmission,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'number'
  },
  LAST_SENDING_DATE: {
    property: PROPERTY_STORE.LAST_SENDING_DATE,
    align: 'left',
    label: labels.LastSendingDate,
    fixed: 'left',
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  DATE_SENT: {
    property: 'lastSendingTime',
    align: 'left',
    label: labels.DATE_SENT,
    fixed: false,
    sortable: true,
    show: true,
    type: 'text',
    width: 180,
    isEditable: false,
    filterableType: 'date'
  },
  DELIVERY_STATUS: {
    property: 'status',
    align: 'center',
    label: labels.DELIVERY_STATUS,
    sortable: true,
    show: true,
    type: 'badge',
    width: 220,
    filterableType: 'select',
    props: {
      style: {
        maxWidth: '100px'
      }
    }
  },
  SMTP: {
    property: PROPERTY_STORE.SMTP,
    align: 'left',
    label: labels.Smtp,
    sortable: true,
    show: true,
    type: 'text',
    width: 160,
    filterableType: 'text'
  },
  ACTIVITY_TYPE: {
    property: PROPERTY_STORE.ACTIVITYTYPE,
    align: 'left',
    label: labels.ActivityType,
    fixed: false,
    sortable: true,
    show: true,
    type: 'slot',
    width: 180,
    isEditable: false,
    filterableType: 'select',
    filterableItems: [
      { text: 'Human Activity', value: '0' },
      { text: 'Bot Activity', value: '1' }
    ]
  }
}
