import useAIDescriptionGeneration from '@/hooks/useAIDescriptionGeneration'

jest.mock('axios', () => ({
  post: jest.fn()
}))

describe('useAIDescriptionGeneration Hook', () => {
  let axiosMock
  let component

  beforeEach(() => {
    jest.clearAllMocks()
    axiosMock = require('axios')

    component = {
      formData: {
        name: 'Test Training',
        category: 'Security',
        targetAudience: 'Employees',
        compliances: ['GDPR'],
        behaviours: ['Phishing'],
        description: ''
      },
      isGenerateLoading: false,
      hasGenerated: false,
      handleGenerate: jest.fn(),
      ...useAIDescriptionGeneration.methods
    }
  })

  describe('computed', () => {
    describe('canAutoGenerateDescription()', () => {
      const getComputed = (ctx) => {
        return useAIDescriptionGeneration.computed.canAutoGenerateDescription.call(ctx)
      }

      it('should return true when all required fields are filled and description is empty', () => {
        const result = getComputed(component)
        expect(result).toBe(true)
      })

      it('should return false when description is not empty', () => {
        component.formData.description = 'Already has description'
        expect(getComputed(component)).toBe(false)
      })

      it('should return falsy when name is empty', () => {
        component.formData.name = ''
        expect(getComputed(component)).toBeFalsy()
      })

      it('should return falsy when category is empty', () => {
        component.formData.category = ''
        expect(getComputed(component)).toBeFalsy()
      })

      it('should return falsy when targetAudience is empty', () => {
        component.formData.targetAudience = ''
        expect(getComputed(component)).toBeFalsy()
      })

      it('should return false when isGenerateLoading is true', () => {
        component.isGenerateLoading = true
        expect(getComputed(component)).toBe(false)
      })

      it('should return false when hasGenerated is true', () => {
        component.hasGenerated = true
        expect(getComputed(component)).toBe(false)
      })
    })
  })

  describe('methods', () => {
    describe('getAIDescriptionPayload()', () => {
      it('should return correct payload structure', () => {
        const payload = component.getAIDescriptionPayload()

        expect(payload).toEqual({
          name: 'Test Training',
          category: 'Security',
          compliance: ['GDPR'],
          behaviour: ['Phishing'],
          role: 'Employees'
        })
      })

      it('should use empty strings for missing fields', () => {
        component.formData = {
          name: 'Test'
        }

        const payload = component.getAIDescriptionPayload()

        expect(payload.name).toBe('Test')
        expect(payload.category).toBe('')
        expect(payload.compliance).toEqual([])
        expect(payload.behaviour).toEqual([])
        expect(payload.role).toBe('')
      })

      it('should handle undefined formData gracefully', () => {
        component.formData = undefined

        const payload = component.getAIDescriptionPayload()

        expect(payload.name).toBe('')
        expect(payload.category).toBe('')
      })
    })

    describe('generateAIDescription()', () => {
      it('should call axios.post with correct URL and payload', async () => {
        axiosMock.post.mockResolvedValue({ data: { description: 'Generated description' } })

        await component.generateAIDescription({
          name: 'Test',
          category: 'Security',
          role: 'Employee'
        })

        expect(axiosMock.post).toHaveBeenCalledWith(
          'https://ai-description.keepnet-labs-ltd-business-profile4086.workers.dev/description',
          {
            name: 'Test',
            category: 'Security',
            role: 'Employee'
          },
          {
            headers: {
              'Content-Type': 'application/json'
            }
          }
        )
      })

      it('should return generated description from response', async () => {
        axiosMock.post.mockResolvedValue({ data: { description: 'Generated text' } })

        const result = await component.generateAIDescription({
          name: 'Test',
          category: 'Security',
          role: 'Employee'
        })

        expect(result).toBe('Generated text')
      })

      it('should trim input parameters', async () => {
        axiosMock.post.mockResolvedValue({ data: { description: 'Result' } })

        await component.generateAIDescription({
          name: '  Test  ',
          category: '  Security  ',
          role: '  Employee  '
        })

        const callArgs = axiosMock.post.mock.calls[0][1]
        expect(callArgs.name).toBe('Test')
        expect(callArgs.category).toBe('Security')
        expect(callArgs.role).toBe('Employee')
      })

      it('should include existing description if provided and long enough', async () => {
        axiosMock.post.mockResolvedValue({ data: { description: 'Result' } })

        await component.generateAIDescription({
          name: 'Test',
          category: 'Security',
          role: 'Employee',
          description: '  This is a long description  '
        })

        const callArgs = axiosMock.post.mock.calls[0][1]
        expect(callArgs.description).toBe('This is a long description')
      })

      it('should not include description if too short', async () => {
        axiosMock.post.mockResolvedValue({ data: { description: 'Result' } })

        await component.generateAIDescription({
          name: 'Test',
          category: 'Security',
          role: 'Employee',
          description: 'Short'
        })

        const callArgs = axiosMock.post.mock.calls[0][1]
        expect(callArgs.description).toBeUndefined()
      })

      it('should throw error on API failure', async () => {
        const error = new Error('API Error')
        axiosMock.post.mockRejectedValue(error)

        await expect(
          component.generateAIDescription({
            name: 'Test',
            category: 'Security',
            role: 'Employee'
          })
        ).rejects.toThrow('API Error')
      })

      it('should handle empty response', async () => {
        axiosMock.post.mockResolvedValue({ data: {} })

        const result = await component.generateAIDescription({
          name: 'Test',
          category: 'Security',
          role: 'Employee'
        })

        expect(result).toBe('')
      })
    })

    describe('generateDescriptionIfNeeded()', () => {
      it('should generate description if required fields are filled and description is empty', async () => {
        axiosMock.post.mockResolvedValue({ data: { description: 'Generated' } })
        component.handleGenerate.mockResolvedValue(undefined)

        const result = await component.generateDescriptionIfNeeded()

        expect(component.handleGenerate).toHaveBeenCalled()
        expect(result).toBe(true)
      })

      it('should return false if required fields are not filled', async () => {
        component.formData.name = ''

        const result = await component.generateDescriptionIfNeeded()

        expect(component.handleGenerate).not.toHaveBeenCalled()
        expect(result).toBe(false)
      })

      it('should return false if description is already filled', async () => {
        component.formData.description = 'Already has description'

        const result = await component.generateDescriptionIfNeeded()

        expect(component.handleGenerate).not.toHaveBeenCalled()
        expect(result).toBe(false)
      })

      it('should return false if isGenerateLoading is true', async () => {
        component.isGenerateLoading = true

        const result = await component.generateDescriptionIfNeeded()

        expect(component.handleGenerate).not.toHaveBeenCalled()
        expect(result).toBe(false)
      })

      it('should return false if description is only whitespace', async () => {
        component.formData.description = '   '

        const result = await component.generateDescriptionIfNeeded()

        expect(component.handleGenerate).toHaveBeenCalled()
        expect(result).toBe(true)
      })

      it('should handle missing formData gracefully', async () => {
        component.formData = undefined

        const result = await component.generateDescriptionIfNeeded()

        expect(result).toBe(false)
      })
    })
  })
})
