<template>
  <div class="input-ai-description__container">
    <div v-if="isGenerating" class="input-ai-description__skeleton">
      <div class="input-ai-description__skeleton-wrapper">
        <div
          class="input-ai-description__skeleton-line input-ai-description__skeleton-line--long"
        ></div>
        <div
          class="input-ai-description__skeleton-line input-ai-description__skeleton-line--medium"
        ></div>
        <div
          class="input-ai-description__skeleton-line input-ai-description__skeleton-line--short"
        ></div>
      </div>
      <div class="input-ai-description__generating-badge">
        <img
          src="@/assets/img/spinner.svg"
          class="input-ai-description__generating-spinner"
          alt="spinner"
        />
        <span>Generating...</span>
      </div>
    </div>
    <template v-else>
      <v-textarea
        v-bind="requiredProps"
        :value="value"
        :id="id"
        outlined
        dense
        auto-grow
        autocomplete="disabled"
        :rows="rows"
        :min-height="minHeightNumber"
        :disabled="disabled"
        :placeholder="placeholder"
        :rules="rules"
        :readonly="readonly"
        :hint="hint"
        @input="$emit('input', $event)"
      />
      <div
        v-if="showGenerateButton || $slots['append-inner']"
        class="input-ai-description__button-overlay"
      >
        <template v-if="showGenerateButton">
          <v-tooltip bottom opacity="1" z-index="1000" max-width="250">
            <template #activator="{ on }">
              <div v-on="on">
                <v-btn
                  class="generate-button safari-hide-tooltip"
                  :color="hasGenerated ? '#2196F3' : '#2196F3'"
                  :outlined="hasGenerated"
                  rounded
                  :style="getGenerateButtonStyle"
                  @click="handleGenerateClick"
                >
                  <v-icon
                    left
                    :color="hasGenerated ? '#2196F3' : 'white'"
                    style="margin-right: 4px; font-size: 16px"
                    >mdi-creation</v-icon
                  >
                  <span
                    :style="{
                      color: hasGenerated ? '#2196F3' : 'white',
                      fontSize: '12px',
                      fontWeight: 600,
                      textTransform: 'capitalize',
                    }"
                    >{{ generateButtonText }}</span
                  >
                </v-btn>
              </div>
            </template>
            <span>{{ tooltipMessage }}</span>
          </v-tooltip>
        </template>
        <slot v-else name="append-inner"></slot>
      </div>
      <div
        v-if="showGeneratedByAI || hasGenerated"
        class="input-ai-description__generated-badge"
      >
        Generated by AI Ally
      </div>
    </template>
  </div>
</template>

<script>
import * as Validations from "@/utils/validations";
import labels from "@/model/constants/labels";
export default {
  name: "InputAIDescription",
  props: {
    value: {
      type: String,
    },
    id: {
      type: String,
    },
    initialPlaceholder: {
      type: String,
      default: "",
    },
    initialRules: {
      type: Array,
    },
    entityName: {
      type: String,
      default: labels.Description,
    },
    required: {
      type: Boolean,
      default: false,
    },
    maxLength: {
      type: Number,
      default: 2000,
    },
    disabled: {
      default: false,
    },
    readonly: {
      default: false,
    },
    applyRules: {
      default: true,
    },
    height: {
      type: String,
    },
    rows: {
      type: String,
    },
    hint: {
      type: String,
    },
    showGeneratedByAI: {
      type: Boolean,
      default: false,
    },
    isGenerating: {
      type: Boolean,
      default: false,
    },
    showGenerateButton: {
      type: Boolean,
      default: false,
    },
    hasGenerated: {
      type: Boolean,
      default: false,
    },
    isGenerateDisabled: {
      type: Boolean,
      default: false,
    },
    tooltipMessage: {
      type: String,
      default: "",
    },
  },
  data() {
    return {
      rules: [
        (v) => Validations.startsWithSpace(v, labels.CannotStartWithSpace),
        (v) =>
          Validations.maxLength(
            v,
            this.maxLength,
            labels.getMaxLengthMessage(this.entityName, this.maxLength)
          ),
      ],
      placeholder: "",
      requiredProps: {},
    };
  },
  computed: {
    minHeightNumber() {
      if (this.height) {
        return this.height.includes("px") ? this.height.replace("px", "") : this.height;
      }
      return undefined;
    },
    textareaStyle() {
      if (this.height) {
        const heightValue = this.height.includes("px") ? this.height : `${this.height}px`;
        return {
          "--textarea-min-height": heightValue,
        };
      }
      return {};
    },
    getGenerateButtonStyle() {
      const defaultStyle = {
        textTransform: "capitalize",
        maxHeight: "28px",
      };
      if (this.isGenerateDisabled || this.isGenerating) {
        return {
          opacity: 0.5,
          pointerEvents: "none",
          ...defaultStyle,
        };
      }
      return defaultStyle;
    },
    generateButtonText() {
      if (this.hasGenerated) {
        return "Regenerate";
      }
      if (this.value && this.value.trim().length > 5 && !this.hasGenerated) {
        return "Improve with AI";
      }
      return "Generate";
    },
  },
  watch: {
    required(val) {
      if (val) {
        this.requiredProps = {
          hint: this.hint || labels.RequiredStar,
          persistentHint: true,
        };
        this.rules.unshift((v) => Validations.required(v));
      }
      this.rules = this.applyRules ? this.initialRules || this.rules : [];
      this.placeholder = this.initialPlaceholder || labels.EnterDescription;
    },
  },
  created() {
    if (this.required) {
      this.requiredProps = {
        hint: this.hint || labels.RequiredStar,
        persistentHint: true,
      };
      this.rules.unshift((v) => Validations.required(v));
    }
    this.rules = this.applyRules ? this.initialRules || this.rules : [];
    this.placeholder = this.initialPlaceholder || labels.EnterDescription;
  },
  methods: {
    handleGenerateClick() {
      if (this.isGenerateDisabled || this.isGenerating) {
        return;
      }
      this.$emit("generate");
    },
  },
};
</script>

<style lang="scss">
.input-ai-description__container {
  position: relative;

  .v-textarea {
    margin-bottom: 36px !important;

    .v-input__slot {
      padding-bottom: 50px !important;
    }

    textarea {
      padding-right: 0 !important;
    }
  }
}

.input-ai-description__button-overlay {
  position: absolute;
  bottom: 32px;
  right: 16px;
  z-index: 10;
}

.input-ai-description__generated-badge {
  position: absolute;
  bottom: 32px;
  left: 8px;
  z-index: 20;
  color: #383b41;
  font-size: 12px;
  font-style: normal;
  font-weight: 400;
  line-height: 19px;
  opacity: 0.5;
  pointer-events: none;
  background-color: #ffffff;
  padding: 2px 4px;
}

.input-ai-description__skeleton {
  position: relative;
  padding: 16px;
  border: 1px solid rgba(0, 0, 0, 0.12);
  border-radius: 4px;
  background-color: #ffffff;
  min-height: 100px;
  overflow: hidden;
}

.input-ai-description__skeleton-wrapper {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.input-ai-description__skeleton-line {
  height: 16px;
  border-radius: 10px;
  background: linear-gradient(
    90deg,
    rgba(179, 212, 252, 0.3) 0%,
    rgba(179, 212, 252, 0.5) 50%,
    rgba(179, 212, 252, 0.3) 100%
  );
  background-size: 200% 100%;
  animation: skeleton-shimmer 2s ease-in-out infinite;

  &--long {
    width: 100%;
  }

  &--medium {
    width: 75%;
  }

  &--short {
    width: 50%;
  }
}

.input-ai-description__generating-badge {
  position: absolute;
  bottom: 8px;
  right: 16px;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  background-color: #2196f3;
  border-radius: 18px;
  color: white;
  opacity: 0.5;
  font-size: 12px;
  font-weight: 600;
  font-family: "Open Sans", sans-serif;
}

.input-ai-description__generating-spinner {
  width: 16px;
  height: 16px;
  animation: spin 1s linear infinite;
}

@keyframes skeleton-shimmer {
  0% {
    background-position: 100% 0;
  }
  100% {
    background-position: -100% 0;
  }
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
