<template>
  <div class="input-ai-description__container">
    <div v-if="isGenerating" class="input-ai-description__skeleton">
      <div class="input-ai-description__skeleton-wrapper">
        <div
          class="input-ai-description__skeleton-line input-ai-description__skeleton-line--long"
        ></div>
        <div
          class="input-ai-description__skeleton-line input-ai-description__skeleton-line--medium"
        ></div>
        <div
          class="input-ai-description__skeleton-line input-ai-description__skeleton-line--short"
        ></div>
      </div>
      <div class="input-ai-description__generating-badge">
        <img
          src="@/assets/img/spinner.svg"
          class="input-ai-description__generating-spinner"
          alt="spinner"
        />
        <span>Generating...</span>
      </div>
    </div>
    <template v-else>
      <v-textarea
        v-bind="requiredProps"
        :value="value"
        :id="id"
        outlined
        dense
        auto-grow
        autocomplete="disabled"
        :rows="rows"
        :min-height="minHeightNumber"
        :disabled="disabled"
        :placeholder="placeholder"
        :rules="rules"
        :readonly="readonly"
        :hint="hint"
        @input="$emit('input', $event)"
      />
      <div v-if="$slots['append-inner']" class="input-ai-description__button-overlay">
        <slot name="append-inner"></slot>
      </div>
      <div v-if="showGeneratedByAI" class="input-ai-description__generated-badge">
        Generated by AI Ally
      </div>
    </template>
  </div>
</template>

<script>
import * as Validations from "@/utils/validations";
import labels from "@/model/constants/labels";
export default {
  name: "InputAIDescription",
  props: {
    value: {
      type: String,
    },
    id: {
      type: String,
    },
    initialPlaceholder: {
      type: String,
      default: "",
    },
    initialRules: {
      type: Array,
    },
    entityName: {
      type: String,
      default: labels.Description,
    },
    required: {
      type: Boolean,
      default: false,
    },
    maxLength: {
      type: Number,
      default: 2000,
    },
    disabled: {
      default: false,
    },
    readonly: {
      default: false,
    },
    applyRules: {
      default: true,
    },
    height: {
      type: String,
    },
    rows: {
      type: String,
    },
    hint: {
      type: String,
    },
    showGeneratedByAI: {
      type: Boolean,
      default: false,
    },
    isGenerating: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      rules: [
        (v) => Validations.startsWithSpace(v, labels.CannotStartWithSpace),
        (v) =>
          Validations.maxLength(
            v,
            this.maxLength,
            labels.getMaxLengthMessage(this.entityName, this.maxLength)
          ),
      ],
      placeholder: "",
      requiredProps: {},
    };
  },
  computed: {
    textareaStyle() {
      if (this.height) {
        const heightValue = this.height.includes("px") ? this.height : `${this.height}px`;
        return {
          "--textarea-min-height": heightValue,
        };
      }
      return {};
    },
  },
  watch: {
    required(val) {
      if (val) {
        this.requiredProps = {
          hint: this.hint || labels.RequiredStar,
          persistentHint: true,
        };
        this.rules.unshift((v) => Validations.required(v));
      }
      this.rules = this.applyRules ? this.initialRules || this.rules : [];
      this.placeholder = this.initialPlaceholder || labels.EnterDescription;
    },
  },
  created() {
    if (this.required) {
      this.requiredProps = {
        hint: this.hint || labels.RequiredStar,
        persistentHint: true,
      };
      this.rules.unshift((v) => Validations.required(v));
    }
    this.rules = this.applyRules ? this.initialRules || this.rules : [];
    this.placeholder = this.initialPlaceholder || labels.EnterDescription;
  },
};
</script>

<style>
.input-ai-description__container {
  position: relative;
}

.input-ai-description__container :deep(.v-textarea .v-input__slot) {
  padding-bottom: 50px !important;
}

.input-ai-description__button-overlay {
  position: absolute;
  bottom: 32px;
  right: 16px;
  z-index: 10;
}

.input-ai-description__generated-badge {
  position: absolute;
  bottom: 36px;
  left: 16px;
  z-index: 10;
  color: var(--Black-Black, #383b41);
  font-feature-settings: "liga" off, "clig" off;
  font-family: "Open Sans", sans-serif;
  font-size: 12px;
  font-style: normal;
  font-weight: 400;
  line-height: 19px;
  opacity: 0.5;
}

.input-ai-description__skeleton {
  position: relative;
  padding: 16px;
  border: 1px solid rgba(0, 0, 0, 0.12);
  border-radius: 4px;
  background-color: #ffffff;
  min-height: 100px;
  overflow: hidden;
}

.input-ai-description__skeleton-wrapper {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.input-ai-description__skeleton-line {
  height: 16px;
  border-radius: 10px;
  background: linear-gradient(
    90deg,
    rgba(179, 212, 252, 0.3) 0%,
    rgba(179, 212, 252, 0.5) 50%,
    rgba(179, 212, 252, 0.3) 100%
  );
  background-size: 200% 100%;
  animation: skeleton-shimmer 2s ease-in-out infinite;

  &--long {
    width: 100%;
  }

  &--medium {
    width: 75%;
  }

  &--short {
    width: 50%;
  }
}

.input-ai-description__generating-badge {
  position: absolute;
  bottom: 8px;
  right: 16px;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  background-color: #2196f3;
  border-radius: 18px;
  color: white;
  font-size: 12px;
  font-weight: 600;
  font-family: "Open Sans", sans-serif;
}

.input-ai-description__generating-spinner {
  width: 16px;
  height: 16px;
  animation: spin 1s linear infinite;
}

@keyframes skeleton-shimmer {
  0% {
    background-position: 100% 0;
  }
  100% {
    background-position: -100% 0;
  }
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
